### PR TITLE
Prevent maximum call stack from being exceeded

### PR DESCRIPTION
**Pull request by Asuza**
- This is a fix for cucumber/cucumber-js#496

### CODE REVIEW

**Comment by Asuza** [comment]
I can't run `npm test` on master without failing tests, even without my change. Not sure what to do here.

**Comment by charlierudolph** [comment]
We want to also work in the browser, so this should either use setTimeout, or we need to abstract this in such a way that we can detect if process is available and use nextTick in that case and otherwise use setTimeout.

CI only shows a unit test failing related to your change. What tests are failing for you?

**Comment by Asuza** [comment]
I'm getting quite a few errors. I've removed the stack traces, but this is the rest:
```
Failures:
1) Cucumber.Runtime.AstTreeWalker visitScenario() when not failing fast or no failure has been encountered sets the new World instance
  Message:
    Expected spy setWorld to have been called with [ spy on world instance ] but it was never called.

2) Cucumber.Runtime.AstTreeWalker visitScenario() when not failing fast or no failure has been encountered witnesses a new scenario
  Message:
    Expected spy witnessNewScenario to have been called with [ Object({ mock: spy on scenario.mock }) ] but actual calls were [  ].

3) Cucumber.Runtime.AstTreeWalker visitScenario() when not failing fast or no failure has been encountered creates before and after steps for around hooks
  Message:
    Expected spy createBeforeAndAfterStepsForAroundHooks to have been called with [ Object({ mock: spy on scenario.mock }) ] but it was never called.

4) Cucumber.Runtime.AstTreeWalker visitScenario() when not failing fast or no failure has been encountered creates before steps for before hooks
  Message:
    Expected spy createBeforeStepsForBeforeHooks to have been called with [ Object({ mock: spy on scenario.mock }) ] but it was never called.

5) Cucumber.Runtime.AstTreeWalker visitScenario() when not failing fast or no failure has been encountered creates after steps for after hooks
  Message:
    Expected spy createAfterStepsForAfterHooks to have been called with [ Object({ mock: spy on scenario.mock }) ] but it was never called.

6) Cucumber.Runtime.AstTreeWalker visitScenario() when not failing fast or no failure has been encountered creates a new event about the scenario
  Message:
    Expected spy Event to have been called with [ 'Scenario', Object({ scenario: Object({ mock: spy on scenario.mock }) }) ] but it was never called.

7) Cucumber.Runtime.AstTreeWalker visitScenario() when not failing fast or no failure has been encountered broadcasts the visit of the scenario
  Message:
    Expected spy broadcastEventAroundUserFunction to have been called.
  Message:
    Expected spy on broadcastEventAroundUserFunction to have been called with value as nth parameter spy on scenario visit event, 1.
  Message:
    Expected spy on broadcastEventAroundUserFunction to have been called with a function as nth parameter 2.
  Message:
```

**Comment by Asuza** [comment]
I was able to get down to one problematic test by changing my code a little bit. Seeing if I can figure out how to update the test now.

**Comment by Asuza** [comment]
@charlierudolph, the tests are failing only for old versions of node now. Do you have any suggestions?
Also, wouldn't "process.nextTick" be handled by browserify? I'm relatively new to node, so forgive me if that's a stupid question.

**Comment by charlierudolph** [comment]
I hadn't used browserify enough to know that. After a quick look at the docs and one experiment, it is supported.

**Comment by charlierudolph** [comment]
In 0.10 and 0.12, nextTick didn't accept arguments to pass to the function. Thoughts on just wrapping it?
```js
process.nextTick(function() {
  self.processStep(step, callback);
});
```
I don't think we want to drop support for 0.12 just yet.

**Comment by Asuza** [comment]
Well, I finally got it all passing. I'm not happy with the way I had to change the test, as it's a lot weaker now, but I don't know how to architect it in a reasonable way for it to be tested as well as it was in my previous commit.

**Comment by charlierudolph** [comment]
Lets change the test to add an extra step. First we ensure it calls process.nextTick. Then we execute the callback passed to process.nextTick and verify it calls processStep.

**Comment by Asuza** [comment]
@charlierudolph I used `process.nextTick` in the test to ensure I waited until the right moment to `expect` certain things to happen. Is there a preferred solution to waiting for `nextTick` to execute?

**Comment by charlierudolph** [comment]
I was thinking of something more like
```js
describe("user function", function () {
  var userFunction, userFunctionCallback;

  beforeEach(function () {
    treeWalker.visitStep(step, callback);
    userFunction         = treeWalker.broadcastEventAroundUserFunction.calls.mostRecent().args[1];
    userFunctionCallback = createSpy("user function callback");
    spyOn(process, 'nextTick');
    spyOn(treeWalker, 'processStep');
  });

  it('calls process.nextTick', function () {
    userFunction (userFunctionCallback);
    expect(process.nextTick).toHaveBeenCalled();
  });

  describe("on next tick", function () {
    var nextTickCallback;
    
    beforeEach(function () {
      nextTickCallback = process.nextTick.calls.mostRecent().args[0];
      spyOn(treeWalker, 'processStep');
    });

    it("processes the step", function () {
      nextTickCallback();
      expect(treeWalker.processStep).toHaveBeenCalledWith(step, callback);
    });
  });
});
```

**Comment by Asuza** [comment]
Do you want to update the tests after this gets merged, or would you rather I just copy and paste what you suggested? I don't have enough experience with Jasmine to suggest anything is or isn't a good idea.

**Comment by Asuza** [comment]
Besides, in this portion that you posted:
```javascript
    beforeEach(function () {
      nextTickCallback = process.nextTick.calls.mostRecent().args[0];
      spyOn(treeWalker, 'processStep');
    });
```
`mostRecent()` appears to be undefined. `process.nextTick` probably hasn't executed at that point.

**Comment by charlierudolph** [comment]
Please update now. Yeah, looks like we need to move `userFunction (userFunctionCallback);` from the it block its in to the previous beforeEach.

**Pull request closed without merging**
