### PR TITLE
timeout steps that take too long

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros @samccone 

Moved #383 over from my fork to the repo, and reworked the interface

### CODE REVIEW

**Comment by samccone** [comment]
@charlierudolph anyway we can squash this down?

**Comment by charlierudolph** [comment]
I squash merge when actually merging PRs with [git-town](https://github.com/Originate/git-town).

**Comment by jbpros** [comment]
Thanks @charlierudolph. I really like the interface and obviously this is a very nice improvement!

**Comment by jlin412** [comment]
@charlierudolph how do I change default timeout for all steps?

**Comment by jbpros** [comment]
@jlin412 it's [documented](https://github.com/cucumber/cucumber-js#timeouts)

**Pull request closed without merging**
