### PR TITLE
Let step definitions return promises.

### LINKED ISSUE #27: Forgetting to call stepdef callback should fail
* Go to http://cucumber-js.herokuapp.com/
* Comment out callback() in the Given stepdef
* Run
* Nothing happens

I would expect to see an error message saying "callback not called in /^a variable set to (\d+)$/"

### PR DESCRIPTION
**Pull request by samccone**
fixes #173
fixes #27

### CODE REVIEW

**Comment by filipstachura** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cucumber/cucumber-js/193)

Reviewed files:
- lib/cucumber/support_code/step_definition.js @ r1





---

**Comment by jlin412** [comment]
It looks interesting.  Can someone explain to me why we do need this?

**Comment by johngeorgewright** [comment]
:+1:  I would really like this feature.

Selenium webdriver and therefore Protractor use promises. Using cucumber with protractor could be so much easier if promises were handled out of the box.

```js
this.When('I enter "$something" in "$somewhere"', function (text, model, done) {
  element(by.model(model)).sendKeys(text).then(done, done.fail);
});

// compared to...

this.When('I enter "$something" in "$somewhere"', function (text, model) {
  return element(by.model(model)).sendKeys(text);
});
```

**Comment by jlin412** [comment]
That sounds like greAt idea.  Many people are struggling with done callback
when they started.

**Comment by joshthecoder** [comment]
Would be great to get this merged. Right now doing some hackery to patch in promise support by overriding the step methods.

**Comment by benjamine** [comment]
+1

**Comment by dtinth** [comment]
For those who don't want to wait for this pull request to get merged in, you can use [artstep](https://github.com/dtinth/artstep).

It's a more fluent way to write Cucumber.js step definitions.

- For synchronous steps, no need to call `callback()`.
- For asynchronous steps, simply return a Promise or use [ES6 generators](https://www.npmjs.com/packages/co). Which means it also works with:
    - [ES7 async functions](https://github.com/tc39/ecmascript-asyncawait)
    - [asyncawait](https://github.com/yortus/asyncawait)

**Comment by jlin412** [comment]
@samccone and @jbpros What is reason of delaying this feature?
This feature will make cucumber.js so much easier to use.

**Comment by bmustiata** [comment]
If you want to add support for promises and steps without callbacks you can also use [cucumber-promise](https://github.com/bmustiata/cucumber-promise) ([npm link](https://www.npmjs.com/package/cucumber-promise)).

The implementation of [promises](https://github.com/bmustiata/cucumber-promise/blob/master/features/promises.feature) and [steps without callbacks](https://github.com/bmustiata/cucumber-promise/blob/master/features/no-callbacks.feature) are tested with cucumber.js itself, to guarantee it plays nice with your existing tests, and is minimally invasive (just wrap the steps function into one function call).

**Comment by jlin412** [comment]
I like this

**Comment by jbpros** [comment]
Merged in as https://github.com/cucumber/cucumber-js/commit/272dc5e64b4f0e3c9e6704a11b93e9e7cf519906. Released as of 0.5.0.

**Comment by samccone** [comment]
:+1:

**Pull request closed without merging**
