### PR TITLE
update cucumber libraries to latest

### LINKED ISSUE #1571: Cucumber.js 7 fails to generate snippets
Cucumber.js version 7 has an issue when generating the snippets. It fails with

```
TypeError: this.parameterTypes is not a function
    at CucumberExpressionGenerator.createParameterTypeMatchers (/home/runner/work/cucumber-js-test/cucumber-js-test/node_modules/@cucumber/cucumber-expressions/dist/src/CucumberExpressionGenerator.js:110:41)
    at CucumberExpressionGenerator.generateExpressions (/home/runner/work/cucumber-js-test/cucumber-js-test/node_modules/@cucumber/cucumber-expressions/dist/src/CucumberExpressionGenerator.js:27:42)
Error: Process completed with exit code 1.
```

It fails when a snippet is missing. In my example project I just used the [asd](https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md)

What I have found is this fix: https://github.com/cucumber/cucumber-expressions-javascript/commit/4c092a16b169e4e2d50b32112e60cb8d7241c7ef
I guess this could be the issue or there is something wrong with parsing the parameters?

My project currently uses:
 * @cucumber/cucumber: 7.0.0
 * @cucumber/cucumber-expressions: 11.0.1

### PR DESCRIPTION
**Pull request by davidjgoss**
This PR:

- Updates the versions of libraries and updates our code accordingly
- Sets all the versions of `@cucumber/*` dependencies to the exact version - this is definitely debatable as it takes away the possibility for fixes in monorepo libraries getting to users without releasing cucumber-js, but feels safer and more controlled.

This includes a version of `html-formatter` with its dependency tree slimmed down, and this is apparent in our lockfile diff :)

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Ouch my bad! What can we do to make existing `cucumber-js` installations work again?

Should we publish a new cucumber-expressions 11.0.2 that reverts the change in 11.0.1, then re-release the changes in 11.0.1 as 12.0.0?

WDYT @davidjgoss?

**Comment by davidjgoss** [comment]
> Should we publish a new cucumber-expressions 11.0.2 that reverts the change in 11.0.1, then re-release the changes in 11.0.1 as 12.0.0?

Makes sense to me. Then I'll update this branch with 12.0.0 plus the other monorepo updates.

**Review by aslakhellesoy — APPROVED** [review]
LGTM! Thanks David

**Comment by davidjgoss** [comment]
I think it could be worth doing a 7.0.1 release off the back of this, it would close a handful of issues and get a couple of other unreleased fixes out.

**Pull request merged**
