### PR TITLE
New Feature: shared context in beforeAll and afterAll hooks

### LINKED ISSUE #1393: Feature Request: Give BeforeAll a reference to the Cucumber World object
To get around this we've been rolling our own DI which is cumbersome. If this is by intention, I'm wondering why BeforeAll is not given this reference?

### PR DESCRIPTION
**Pull request by BlueMona**
# Description

This is a draft failing scenario to try and describe what @charlierudolph and
@davidjgoss are describing in https://github.com/cucumber/cucumber-js/issues/1393

I'd like to work on a fix but thought it would be best to get feedback on the scenario first.

# Motivation & context

Fixes #1393

## Type of change

- New feature (non-breaking change which adds new behaviour)

# Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mattwynne** [comment]
The scenario we have so far doesn't address the issue around immutability. I suggest we add another scenario showing that even if the first scenario mutates the value that was set in the `BeforeAll` hook, the second scenario gets the original value again. (i.e. we can't use it to leak state between scenarios; each new World instance gets a fresh copy of the `testRunContext`)

**Comment by davidjgoss** [comment]
@BlueMona thanks for getting this going, and great idea to start with the scenario. I think my only suggestion would be for the stuff that we set in `BeforeAll` to be set on the world under its own `testRunContext` property rather than mixed in, so like:

```
Given('first step', function() {
  expect(this.testRunContext.myVar.foo).to.eql(1) 
})
```

Then it's like a sibling of `parameters` and `attach` that you can access from your world (including a custom one).

@mattwynne seems a good direction re immutability.

**Comment by BlueMona** [comment]
The scenario is now passing, but there are a few questions / things left to do. 
- is object an ok type for testRunContext? 
- testRunContext should likely be a property of world, instead of being merged into the root of the object, which would help avoid potential conflicts
- how do we implement this for the worker and how is it tested? 
- do we need a unit test for the testCaseRunner? 
- what about immutability? Should we add a scenario testing for it?

**Comment by davidjgoss** [comment]
Thanks for the update @BlueMona, this is looking good. To your points:

> is object an ok type for testRunContext?

It's kinda the same need as `worldParameters`, which we type as `any`. Technically it should be a JSON-serialisable object so `any` is a bit broad, but there's no nice way to express that in TypeScript at the moment, so I'd say `any` is good for now.

> testRunContext should likely be a property of world, instead of being merged into the root of the object, which would help avoid potential conflicts

I definitely agree, and I'd even go as far as giving each `World` instance a clone of the original `testRunContext` so that if users do modify it, the changes won't bleed into other scenarios running.

> how do we implement this for the worker and how is it tested?

Good question, I'll get back to you! We run the test run hooks once for each worker which makes things...interesting. Testing of parallel stuff is generally in the feature tests.

> what about immutability? Should we add a scenario testing for it?

Yep would be good to test this. Hopefully the cloning idea above would have the desired effect of (enough) immutability. Marking it `readonly` in TypeScript would be an easy win too.

**Comment by mattwynne** [comment]
@davidjgoss thanks for the quick feedback!

I'm wondering if we could achieve the immutability by copying the `testRunContext` when we create the merged `this` object in `invokeStep`.

i.e. something like 

    const world = Object.assign(this.world, { testRunContext: { ...this.testRunContext }})

WDYT?

**Comment by davidjgoss** [comment]
@mattwynne yeah that's basically what I was suggesting, although we'd want a [deep clone](https://www.npmjs.com/package/lodash.clonedeep) since doing a spread just gives you a shallow clone.

**Comment by mattwynne** [comment]
@BlueMona I've extracted a function to run the `BeforeAll` hooks in #1933. We'll want to merge that into this PR before proceeding.

One slightly tricky part of that merge will be sharing the `thisArg` / `testRunContext` with the new function. I suggest adding it as a new argument to the function, but you could also consider making it be the return value, I suppose.

**Comment by kamelbou** [comment]
Hello,

Is it plan to merge this great feature soon ? :)

Thank you

**Comment by mattwynne** [comment]
@BlueMona I had a little look after we finished our session, and I think we still have a couple of other places we need to make a similar change, so that the `thisArg` object in the `runTestRunHooks` function has a _property_ of `testRunContext` rather than _being_ the `testRunContext`.

@davidjgoss as we start to make this distinction between the two, I wonder about how typing could help us here. We could define an explicit `type TestRunContext = any` type and use that everywhere we expect to get a `TestRunContext`, but what about the `world` / `thisArg`? Could we type that as `type World = { testRunContext: TestRunContext }` too? What would be the implications for users who have a custom world? Would this end up being a breaking change?

**Comment by davidjgoss** [comment]
This is shaping up nicely.

@mattwynne for the world I think we should use the existing structures i.e. add `testRunContext` to the constructor object for the built in world and its interface ([here](https://github.com/cucumber/cucumber-js/blob/main/src/support_code_library_builder/world.ts)) and then pass it in when we create the world instance ([here](https://github.com/cucumber/cucumber-js/blob/main/src/runtime/test_case_runner.ts#L92)) - that way we don't have to worry about doing things at step level. I think it'd make sense to type it as `readonly` (like the other props on that object) and also perhaps to [deep clone](https://www.npmjs.com/package/lodash.clonedeep) it each time we do that.

**Comment by davidjgoss** [comment]
Also there are some tests specifically around types that you might want to look at and/or extend https://github.com/cucumber/cucumber-js/blob/main/test-d/world.ts

**Comment by Wepstern** [comment]
Hi,

I am very happy to have found this ticket. It would give us a very powerful tool to describe and manage our test environment. This would avoid the test environment management scattered throughout the code that can cause a lot of headaches.

Huge high five for that! :)

**Review by davidjgoss — CHANGES_REQUESTED** [review]
Looking fantastic, thanks for taking this on Mona. And sorry for the delayed review.

One thing I think we're missing is the correct typing of the `BeforeAll` and `AfterAll` functions so people can access `this.testRunContext` while using TypeScript without a compilation error.

If you go to `test-d/hooks.ts` and add:

```ts
// should allow test run context via this arg in test run hooks
BeforeAll(async function () {
  this.testRunContext.foo = 'bar'
})
AfterAll(async function () {
  this.testRunContext
})
```

Then that will currently fail if you run `npm run types-test`. I think the place to fix it is in `src/support_code_library_builder/types.ts`. We have explicit types for `TestCaseHookFunction` etc there and so it would be good to follow that pattern - although we don't need the complexity with the generics for world there, so it should be easier, something like:

```ts
export type TestRunHookFunction = (
  this: { testRunContext: TestRunContext }
) => any | Promise<any>
```

We'll also need to update some docs:
- https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/api_reference.md#afteralloptions-fn - basic API doc for the functions
- https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/hooks.md#beforeall--afterall - explain how to set test run context
- https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/world.md - explain you can access test run context read only

I'm very happy to help out with any of this as required, just let me know. Thanks again!

**Comment by ksathyanm** [comment]
Just curious if we have any updates or plan for this PR?

**Comment by mattwynne** [comment]
@BlueMona ping me if you want to pair on finishing this off. I'm here to help if you want it.

**Comment by BlueMona** [comment]
Let’s do it this week then!

**Comment by mattwynne** [comment]
> Let’s do it this week then!
> […](#)

@BlueMona great!

Can you use https://calendly.com/mattwynne to book a slot?

**Comment by LANDG-MartinP** [comment]
any news on this PR?

**Comment by davidjgoss** [comment]
Just noting here the idea raised on the issue of, rather than adding a new `testRunContext` concept, just passing in the world parameters and allowing a `BeforeAll` to return a fresh world parameters if it wants to. So like:

```
BeforeAll(async function() {
  this.token = await authenticate(this.parameters.url, this.parameters.clientId, this.parameters.clientSecret)
  return {
    ...this.parameters,
    token
  }
})
```

I think this would solve all the use cases nicely and this PR could be adapted to it without much work - @BlueMona @mattwynne I'm happy to pick this up if you're time-constrained, since I'm working in this area already.

Also somewhat related is #2356 which I'm looking at today.

**Comment by BlueMona** [comment]
David,

Yes, please do.

**Review by davidjgoss — APPROVED** [review]
After some conflict untangling, this fitted together nicely with some other recent changes.

Many thanks @BlueMona for doing most of this!

**Comment by aslakhellesoy** [comment]
Hi @BlueMona,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by iamkenos** [comment]
This one's a great holiday gift. Thanks team 🖤

**Comment by mattwynne** [comment]
🎉 nice one @BlueMona!

**Pull request merged**
