### PR TITLE
update interface

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros 

Implemented the your idea from #679 and got one feature passing. Added it as a static property to Cli for now but may move it once I try and get the browser example to use it. Just a preview if you'd like to look it over before I move on with the rest of the features.

### CODE REVIEW

**Comment by charlierudolph** [comment]
@jbpros Looking at this, I don't see the difference between getting defineSupportCode by requiring cucumber and just having it as a global. Either way it needs to be tied to some static property and allowed to be reset. I don't think its worthwhile to make users require cucumber at the top of every support file

**Comment by jbpros** [comment]
Thanks Charlie, this is great!

Usually, you don't have many files that require Cucumber helpers. For example, in Cucumber Pro, we have 5 stepdef files and 1 hook file. 

That's quite different from our mocha test suite that currently contains 85 files. As I said previously, mocha tests are supposedly more isolated, much more numerous and it's an arguably a nice convenience to have global mocha helpers.

Another nice benefit of the explicit `import`/`require` is that there are no assumptions about the location of support code files. It can be intermixed with other things without any risks.

Another one is linting: global helpers need special linting rules or disabling the linter in some places; that's annoying.

So, I'd really like to be good citizens and not pollute the global scope :)

**Comment by charlierudolph** [comment]
@jbpros this is now ready to go if you'd like to take a look. Got it working in the browser as well (checking it out locally will not work as the dist folder needs to be updated and that is only done on releases but I did it temporarily to test). See the updated `example` folder.

**Comment by jbpros** [comment]
Thank s @charlierudolph, I like this!

I think this deserves a 3.0 release. WDYT?

**Comment by charlierudolph** [comment]
Since 2.0 hasn't been released yet (still a release candidate) I thought it made since to just bundle it into that

**Comment by jbpros** [comment]
Ah! of course, yes. I'm just taking 2.0rc for granted already, using it without any issues ;)

**Pull request closed without merging**
