### PR TITLE
Add basic support for passing in data to the world from the volatile con...

### PR DESCRIPTION
**Pull request by bspates**
...figuration. This does not affect running Cucumberjs from the Cli.

### CODE REVIEW

**Comment by jbpros** [comment]
Can you share some use cases for this please, @bspates?

**Comment by charlierudolph** [comment]
@bspates can you please provide some more details explanation of this use case

**Comment by jbpros** [comment]
Considering closing this PR. I don't understand what this addresses. Please explain @bspates

**Comment by charlierudolph** [comment]
Closing due to age and lack of details about the use case. @bspates please reopen if needed.

**Pull request closed without merging**
