### PR TITLE
documentation: Updated step_definitions.md

### PR DESCRIPTION
**Pull request by w-green**
updated step_definitions.md docs to remove outdated `this` reference

### CODE REVIEW

**Comment by charlierudolph** [comment]
Thanks! There also appears to be a `this.setDefinitionFunctionWrapper` in this file. Could you please update that as well?

**Comment by aslakhellesoy** [comment]
M

**Comment by charlierudolph** [comment]
@aslakhellesoy reopening this as it appears you closed it by mistake. Please comment otherwise.

**Comment by aslakhellesoy** [comment]
Ooops that must have been my unlocked phone in my pocket. I wasn't even looking at this issue!?

**Comment by charlierudolph** [comment]
Thanks!

**Pull request merged**
