### PR TITLE
Fix World code examples in README.md

### PR DESCRIPTION
**Pull request by renegare**
Hi,

Was stuck with the examples given on the README for moment. I believe it needs to be updated?

### CODE REVIEW

**Comment by samccone** [comment]
hi @renegare did this change work for you?

**Comment by renegare** [comment]
Nope :) but either way I think something needs to change. best to close this?

**Comment by samccone** [comment]
yeah lets close this, but feel free to open an issue describing this problem so that we can put in a real fix

thanks @renegare :clap:

**Comment by jbpros** [comment]
It's not recommended to expose the World constructor at the root of a module as it might be executed by cucumber's support code autoloading. The current README looks good to me.

**Pull request closed without merging**
