### PR TITLE
Add error formatting option

### PR DESCRIPTION
**Pull request by joshtombs**

### CODE REVIEW

**Comment by charlierudolph** [comment]
@joshtombs can you please describe a use case for this? I don't understand why this is needed

**Comment by jbpros** [comment]
@joshtombs please tell us what this is addressing exactly. Also, this probably needs some additional scenarios.

**Comment by charlierudolph** [comment]
Closing due to age and lack of details about the use case. @joshtombs please reopen if needed.

**Comment by joshtombs** [comment]
@jbpros @charlierudolph  sorry about the delayed response, but @samccone might be able to add input on use case, as I am a bit removed from this PR. Originally it had to do with a javascript DSL that was built on top of cucumber, and we thought it was nice to be able to display "pretty" errors with different forms of highlighting, filtering and clipping of errors to allow for possibly a trace of 4-5 calls as opposed to the standard 50.

**Comment by charlierudolph** [comment]
Starting 0.4.9, stack traces are "filtered" (removing any lines related to cucumber-js). Are there other lines that would need to be filtered?

**Pull request closed without merging**
