### PR TITLE
timeout steps that take too long

### LINKED ISSUE #27: Forgetting to call stepdef callback should fail
* Go to http://cucumber-js.herokuapp.com/
* Comment out callback() in the Given stepdef
* Run
* Nothing happens

I would expect to see an error message saying "callback not called in /^a variable set to (\d+)$/"

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros @samccone 

Sets the default timeout for a step definition as 10 seconds and this be overridden in the world object and for specific steps.

- Uncertain in 10 seconds is the best default.
- Want to add timeout to hooks in another PR

fixes #27, related to #332

### CODE REVIEW

**Comment by charlierudolph** [comment]
A test case I know needs to be in here is what happens when a function throws an error after it times out.

To solve that I think each step should have its own domain (I noticed this was changed in this [commit](https://github.com/cucumber/cucumber-js/commit/b35cb08c35e9290abb7b36f83f0cfc959d1577eb) and would like to discuss bringing it back). When an error is raised by a step after it times out it can just be safely ignored. Using this approach could also help greatly with #331 as you can tell when a callback is used multiple times and then report it at the end of the suite. I'd be happy to tackle this is in a separate PR and leave this blocking for now.

**Comment by imjacobclark** [comment]
This is a nice to have. In production, we're seeing Cucumbers timeout and fail our builds. Currently working around this with a setTimeout via before and after hooks.

So, +1, lgtm.

**Comment by jbpros** [comment]
This is great! 

So far, we managed to keep World instances untouched by Cucumber. This PR changes that. Are we cool with that?

I don't see any other straightforward/user-friendly way of setting the timeouts. So I'm ok with this. Any thoughts?

**Comment by charlierudolph** [comment]
Another possible interface could be
```js
module.export = function() {
  this.World = //... 
  this.defaultTimeout = //...
  this.Giver(/a step/, {timeout: 10000}, function() {});
}
```

**Comment by charlierudolph** [comment]
Moved to #419

**Pull request closed without merging**
