### PR TITLE
update supported node versions

### PR DESCRIPTION
**Pull request by charlierudolph**

### CODE REVIEW

**Review by davidjgoss — CHANGES_REQUESTED** [review]
Fantastic, we can start landing those other breaking changes for 8.0.0 now. It'll also make the ESM thing smaller and easier.

I think we need to update [the `package.json`](https://github.com/cucumber/cucumber-js/blob/main/package.json#L168) as well.

**Review by davidjgoss — APPROVED** [review]

**Comment by charlierudolph** [comment]
Hmm, I don't understand how the 15.x test builds are marked as required (same with audit dependencies)

**Comment by charlierudolph** [comment]
I think we should be okay to merge this even if we want to get our other fixes on the 7 releases. We should create a 7.x branch and can backport fixes there if need be. Would just want to be sure have the fixes / changelog in the main line branch as well.

**Review by davidjgoss — APPROVED** [review]
> We should create a 7.x branch and can backport fixes there if need be.

Good point, I'll do that.

Not sure what's with the phantom 15.x build showing up, seems to still be doing it even after a merge - hopefully will clear itself when it lands on `main`.

**Pull request merged**
