### PR TITLE
Run scenarios in parallel

### PR DESCRIPTION
**Pull request by charlierudolph**
Kills the BeforeFeature / AfterFeature hook as those events would prevent scenarios from different features from being run in parallel.

### CODE REVIEW

**Comment by charlierudolph** [comment]
This is blocked on #859 where we would update the formatters to batch scenario output when running in parallel

**Comment by charlierudolph** [comment]
Going to close this for now. I want to implement #870 first anyway. Can come back to this afterward. Once #870 is in, this should no longer be a breaking change

**Comment by kidwm** [comment]
@charlierudolph is it possible to run features in parallel with v3 now?

**Comment by charlierudolph** [comment]
Nope. This should be able to be revisited now though

**Pull request closed without merging**
