### PR TITLE
fix(message-streams): defined direct dependency to satisfy gherkin-streams peer requirement for consumers

### LINKED ISSUE #2005: peer dependency not fulfilled in latest release
### 👓 What did you see?

i've been getting renovate PRs for the latest release (v8.1.0). when running `npm ls` to ensure that all peer dependency requirements are met (i run this as part of my standard verification for most projects), it fails reporting:

> npm ERR! peer dep missing: @cucumber/message-streams@>=4.0.0, required by @cucumber/gherkin-streams@5.0.1

([example failure](https://github.com/form8ion/lift/runs/6100616753?check_suite_focus=true#step:5:86))

### ✅ What did you expect to see?

`npm ls` should exit with an exit code of zero and not report missing peer dependencies. ideally the `@cucumber/cucumber` package should declare a direct dependency on the `@cucumber/message-streams` package so that the peer requirement is not passed along to consumers of `@cucumber/cucumber`

### 📦 Which tool/library version are you using?

`@cucumber/cucumber` v8.1.0

### 🔬 How could we reproduce it?

* https://github.com/form8ion/lift/pull/628
* https://github.com/form8ion/lift/runs/6100616753?check_suite_focus=true#step:5:86
* if cloning the branch for that PR, simply install the proper dependencies with `npm install` and run verification with `npm test`

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

### PR DESCRIPTION
**Pull request by travi**
closes #2005

### 🤔 What's changed?

defined direct dependency to satisfy gherkin-streams peer requirement for consumers

### ⚡️ What's your motivation? 

fixes #2005 

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by travi** [comment]
i see that dependency-lint is failing due to this change. i'm not familiar with that specific tool, but i disagree with its guidance in this case unless i'm overlooking something about this situation. i'm interested in feedback from the team about whether passing this unsatisfied peer requirement on to consumers is intentional in this case.

**Review by davidjgoss — APPROVED** [review]

**Comment by aslakhellesoy** [comment]
Hi @travi,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by davidjgoss** [comment]
Thanks @travi - released in v8.1.1 just now.

**Comment by travi** [comment]
thanks a lot, @davidjgoss!

**Pull request merged**
