### PR TITLE
(fix) Add missing testStepResult.exception to result object

### PR DESCRIPTION
**Pull request by gd46**

### CODE REVIEW

**Comment by gd46** [comment]
Closes #949

**Comment by charlierudolph** [comment]
Cool! Please get the tests passing. There appears to be a lint issue currently and hopefully you'll also need to update a test

**Comment by gd46** [comment]
I fixed the lint errors, and Im looking at the tests. Will have another update soon.

**Comment by gd46** [comment]
Should be good now, let me know if there is anything needed.

**Comment by gd46** [comment]
@charlierudolph Do you need anything else from me on this one?

**Pull request merged**
