### PR TITLE
WIP: feat(support-code): Allow direct import

### PR DESCRIPTION
**Pull request by nicojs**
Allow direct import of support code:

```javascript
const { 
  Given,
  When,
  Then,
  Before,
  After,
  defineParameterType, 
  addTransform, 
  defineStep, 
  registerHandler, 
  registerListener, 
  setDefaultTimeout, 
  setDefinitionFunctionWrapper, 
  setWorldConstructor 
} = require('cucumber');
```

Todo:
- [ ] Decide if we're keeping the `defineSupportCode`
- [ ] Update all feature files (or write new ones, if we decide to keep `defineSupportCode`)
- [ ] Update all docs (or add to the existing docs of we decide to keep `defineSupportCode`)

I personally think that its better to not export `defineSupportCode` from `cucumber` anymore. It will simplify the docs and features. I know there will initially be a pain for existing code that would need to be rewritten, but it will be much simpler in the end.

Note: related PR #828 was my first attempt.

Fixes issue #770

### CODE REVIEW

**Comment by nicojs** [comment]
I already updated _some_ features but i want to wait with rewriting the rest until we decided on the fate of `defineSupportCode`

**Comment by nicojs** [comment]
@charlierudolph who do we need to make the decision? Can we make it or do we need other people?

**Comment by charlierudolph** [comment]
For now I'd suggest we just leave `defineSupportCode`. If we want to remove it, I'd say lets just add a deprecation warning to it and can remove it at the next major version. 

@jbpros figured you might like to take a look at this since we had discussed something like this with the initial changeover.

@aslakhellesoy @mattwynne thoughts on converting the `Given`, `When`, `Then` to lowercase as in javascript typically only classes start with uppercase letters.

**Comment by nicojs** [comment]
Good point! I'll add the deprecated message if @jbpros agrees. Then I'll start working on updating the features and docs.

I kept the uppercase `Given`, `When`, `Then`, `After` and `Before` around for now, but I would suggest deprecating them as well if everyone agrees lowercase is the way to go. It cleans up the api further IMHO, especially since all the other support methods are lowercase as well.

**Comment by aslakhellesoy** [comment]
Function/method names starting with a lowercase is non-idiomatic in many programming languages. Some examples are Ruby, JavaScript and Java.

Cucumber intentionally broke this convention from the start. Cucumber-Ruby defines a method named `Given`. So does Cucumber-JVM (Java 8), and Cucumber.js.

I can't recall that anyone has had any issue with it, and it has become one of characteristic traits of Cucumber. I highly value this quirk, and I think it is something we should keep.

Cucumber has a few of its own idioms, and they should be used even if they sometimes conflict with language idioms.

**Comment by nicojs** [comment]
> Function/method names starting with a lowercase is idiomatic in many programming languages. Some examples are Ruby, JavaScript and Java.

I do think that for JavaScript it is more important, as it is the only way to keep your sanity in dealing with constructor functions vs regular functions.

> Cucumber has a few of its own idioms, and they should be used even if they sometimes conflict with language idioms.

I didn't know about them. If people feel strongly about it, lets keep it uppercase. Maybe we could add a note to the docs where we explain it to be uppercase by design and that it is NOT a constructor function.

**Comment by aslakhellesoy** [comment]
I suggest we wait until we hear reports of people accidentally writing `new Given()`. Has anyone come across this?

**Comment by nicojs** [comment]
> If we want to remove it, I'd say lets just add a deprecation warning to it and can remove it at the next major version.

@aslakhellesoy Do you agree on deprecating the use of `defineSupportCode`? Is it OK if i go ahead and implement this?

**Comment by aslakhellesoy** [comment]
I don't have strong opinions on that. @charlierudolph and @jbpros' call.

**Comment by charlierudolph** [comment]
@nicojs lets leave `defineSupportCode` for now (with no deprecation). I'll good moving all the code examples to this new syntax but would like to leave that in for now. That also allows all the tests to stay as they and we can switch them over in the future if so desired.

**Comment by charlierudolph** [comment]
For this PR, instead of updating existing tests, can you please add a new feature test?

**Comment by lgandecki** [comment]
Coming from cucumber 1 - I love the proposed cleaner syntax! :)

**Comment by lgandecki** [comment]
@nicojs If you don't have time for this anymore, I'd love to finish this (mostly add new tests). If I don't hear from you in the next 24 hrs I'm gonna run with it. :)

**Comment by lgandecki** [comment]
I made the change in #841

**Comment by charlierudolph** [comment]
closed in favor of #841

**Comment by nicojs** [comment]
Sorry, was quite busy these last month. Glad it got merged anyway.

**Pull request closed without merging**
