### PR TITLE
call callback only once per step execution

### PR DESCRIPTION
**Pull request by akania**
Right now it is possible to call callback fn multiple times in a step definition - this results with abnormal behavior - following/next steps are triggered for every callback invocation - this is simple check to prevent this + print to output that callback was called multiple times for some step.

I think that it improvement is useful during test development because async code based on events may trigger callback fn multiple times - it is not always obvious what is happening.

### CODE REVIEW

**Comment by jbpros** [comment]
Potential fix for #331.

**Comment by jbpros** [comment]
I've [rebased onto master](https://github.com/cucumber/cucumber-js/tree/akania-callbackCalledOnlyOnce) and played a bit with this implementation. Unfortunately, failing a step after it completed leads to weird behaviours, as I expected. When dealing with asynchronous code, double-callback failures might get reported within subsequent scenarios, which makes debugging highly confusing.

 I think a hard fail (i.e. prematurely ending the whole suite run) is the cleanest way to handle multiple callbacks. The "end-of-run multiple callback report" could be another good solution.

Thoughts?

**Comment by charlierudolph** [comment]
I'd vote for just reporting it at the end of run as being called twice.

**Comment by jbpros** [comment]
@akania I agree with @charlierudolph. There's not much we can do apart from reporting the problem (we might fail the run in strict mode too). Do you think this PR is still relevant or should we start from scratch?

**Comment by jbpros** [comment]
I believe this is fixed in 2c5cd12

**Comment by charlierudolph** [comment]
Fixed ish, it doesn't report if they are called twice but it does stop multiple runs from happening.

**Comment by jbpros** [comment]
@charlierudolph I'm happy with that for now.

**Pull request closed without merging**
