### PR TITLE
add TAP formatter

### PR DESCRIPTION
**Pull request by miguelmota**
Added [TAP](https://testanything.org/tap-version-13-specification.html) formatter. This makes it work with [testem](https://github.com/airportyh/testem) and other frameworks that expect to consume TAP formatted output.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
This is awesome! @jbpros I'm a big fan of TAP

**Comment by samccone** [comment]
awesome work @miguelmota 

@jbpros @aslakhellesoy I would love to work with you guys to get this PR in
https://github.com/cucumber/cucumber-js/pull/309

So that instead of adding new formatters to the core of cucumber people can simply write standalone output formatters :)

**Comment by jbpros** [comment]
That's really good, thanks @miguelmota.

@samccone I'd be happy to pair with you. When can you do that?

**Comment by JosePedroDias** [comment]
:+1:

**Comment by charlierudolph** [comment]
closing in favor of #516

**Pull request closed without merging**
