### PR TITLE
remove callback.fail()

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros 

* remove `callback.fail(error)` in favor of `callback(error)` to use just the standard callback interface
* ~~remove `callback.ending()` in favor of not providing a function (taking after mocha)~~

### CODE REVIEW

**Comment by jbpros** [comment]
I'm not sure about removing `pending()`. I think it's useful when copy/pasting stepdef snippets from the terminal for undefined steps. It's particularly useful for beginners: having the function attached to the regexp makes it easier for them to get started. I can see that a lot with less experienced people during our BDD/Cucumber trainings.

I'd rather keep it in and also allow for the "no function at all" syntax as an alternative mean for specifying a pending step.

**Comment by charlierudolph** [comment]
The function is still there. All the user has to do is remove a paren and uncomment some lines. I'll update this so the user doesn't actually need to remove a paren

**Comment by charlierudolph** [comment]
Alternatively what do you think about just returning a string value of 'pending'?

**Comment by charlierudolph** [comment]
Never mind about the updating it so the user doesn't need to remove the paren

**Comment by charlierudolph** [comment]
@jbpros reverted the remove of callback.pending()

**Comment by jbpros** [comment]
Merged in as 53649ec6933c576ab64f96aca5157b80e09d1a54 -- thanks @charlierudolph!

**Pull request closed without merging**
