### PR TITLE
catch ambiguous step definitions

### LINKED ISSUE #176: Duplicated stepdefs do not throwing any error?!
I made two step definitions with completely the same regex in 2 different javascript files under the step_definitions folder as following:
a.js
```
...
 this.When(/^I visit "([^"]*)"$/, function (url, next) {
        console.log('The first one!');
    });
...
```
b.js
```
...
 this.When(/^I visit "([^"]*)"$/, function (url, next) {
        console.log('The second one with totally different implementation~');
    });
...
```

When I ran the test, I figured out that cucumber-js load the 2 files in alphabetical order, so the working definition was actually in 'b.js'. 

I thought it would be unsafe not throwing any error(such as 'Duplicated step definitions') because when we deal with large amount of stepdefs, we cannot guarantee we will not accidentally override previous stepdefs and that would certainly cause lots of troubles.

Did I do it wrong or it is actually an issue with the cucumber-js?

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros 

resolves #176

### CODE REVIEW

**Comment by jbpros** [comment]
@charlierudolph you [wrote](https://github.com/cucumber/cucumber-js/pull/360#issuecomment-136175416) that ambiguous steps shouldn't throw an error but simply be marked as ambiguous. I think they should be failures. Ambiguous steps are the result of a mistake in stepdef patterns that needs to be fixed.

Here is an example of the consequences this can have: consider a scenario which is passing. One of its steps suddenly becomes ambiguous because of a new step definition. That scenario will be reported as ambiguous, which is not considered a failure (Cucumber's return code is still 0). Let's assume the behaviour described in that scenario was modified and got broken recently. It is now possible that nobody will pay attention to it: the build is still green but in fact that piece of behaviour is not tested anymore and is broken.

The strict mode would prevent that situation but we cannot expect everyone to switch it on.

I like the ambiguous scenario/step state this PR introduces. But I think it should be reported as a hard failure (in red!).

**Comment by jlin412** [comment]
@jbpros Though I prefer your approach, it will deviate from the standard in other languages.  I use Ruby cucumber before so I know ambiguous scenario/step state should only fail in strict mode.  I think that it may be sufficient for me as long as there is a warning message so I can debug.

**Comment by charlierudolph** [comment]
In cucumber ruby, ambiguous steps throw an error, stopping the run. @jbpros I consider ambiguous steps similar to undefined steps as for both cucumber can't get the step definition for the step. One is caused by a lack of step definitions and one is too many step definitions. 

I'm happy to make ambiguous steps cause an exit code of 1, but I think undefined steps need to be treated the same way.

**Comment by jbpros** [comment]
I quite like that idea, @charlierudolph. It could be discussed on https://github.com/cucumber/cucumber/issues.

However, one could argue that undefined steps are like empty examples in mocha (`it("does something")` with no function passed as param #2), which I believe will not be considered an error, just "not ready yet".

**Comment by charlierudolph** [comment]
Empty examples in mocha are pending tests and we have out version of pending steps (though I've suggested before switching to mocha's approach for pending steps)

**Comment by charlierudolph** [comment]
Alright @jbpros this is updated so ambiguous steps are by treated as failures. Used "magenta" for the color at the moment since ambiguous is its own status.

**Comment by jbpros** [comment]
:+1: good stuff!

**Pull request closed without merging**
