### PR TITLE
Fix handling of unusual error objects

### PR DESCRIPTION
**Pull request by efokschaner**
Fixes https://github.com/cucumber/cucumber-js/issues/564

### CODE REVIEW

**Comment by efokschaner** [comment]
@charlierudolph Any chance you could review this PR?

**Comment by charlierudolph** [comment]
Love the code change, but the feature tests look a little much to me. I'd think just a single unit test would be enough.

**Comment by efokschaner** [comment]
@charlierudolph I like the feature test because its less prescriptive about where in the system this is handled correctly and is more behaviour-focused. That said, i can remove them and add another unit test if you prefer.

**Comment by charlierudolph** [comment]
I believe the feature test should at least be simplified to be a single formatter and a single step type. 
I'd also like to have a unit test added that showcases a non-error object being converted to a string.

**Comment by efokschaner** [comment]
@charlierudolph Thanks for the clarification. Updated based on your feedback. I've never used jasmine before so please let me know if my changes are best practice etc.

**Comment by charlierudolph** [comment]
So you current two test cases are for "of string type" and "of non-serializable type". Based on the code, shouldn't it be when the "of error type" and "of non-error type"?

**Comment by efokschaner** [comment]
Good point, added a test for Error so now we're verifying that:
1. A string passes through unmodified
2. An Error passes through unmodified
3. An arbitrary object is sanitized to a string.

**Comment by efokschaner** [comment]
@charlierudolph Would you have time to take a look at the latest iteration? Thanks!

**Pull request merged**
