### PR TITLE
Added api reference for And and But methods

### PR DESCRIPTION
**Pull request by silversonicaxel**

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Thanks for the contribution @silversonicaxel.

I actually think we should remove the `And` and `But` methods from the API. At the API level, we can't know whether a step definition will be called from a Gherkin `Given` or a Gherkin `And`.

**Comment by silversonicaxel** [comment]
@aslakhellesoy personally I agree with you, I also never use `And`, but its associated `Given` / `When` / `Then`.
Only concern is, until `And` and `But` are there, I would document them.
But of course up to you!

**Comment by aslakhellesoy** [comment]
Hi @silversonicaxel,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by aslakhellesoy** [comment]
Good point. Merged!

**Comment by charlierudolph** [comment]
I don't understand this. This updated documentation without changing implementation. 

These methods weren't added and thus users cannot define step using And / But.

I also don't think they should if we want to move toward unambiguous keywords down the line (which we would require us to remove defineStep)

**Comment by silversonicaxel** [comment]
The current implementation is now reflected in this new documentation.
If you currently `import { But, And }` from the cucumber steps, you can use these methods to define the commands for a step definition, as it happens for `Given`, `When` and `Then`

**Comment by davidjgoss** [comment]
> If you currently import { But, And } from the cucumber steps, you can use these methods to define the commands for a step definition, as it happens for Given, When and Then

It...definitely doesn't. You can see here that we export `defineStep`, `Given`, `When`  and `Then`. If I test with a project with cucumber-js locally, trying to import `And` or `But` errors like I'd expect. You can use them in feature files but you can't define steps with them.

Are you using another tool that wraps cucumber-js?

**Comment by silversonicaxel** [comment]
https://github.com/cucumber/cucumber-js/pull/1613

**Comment by davidjgoss** [comment]
@silversonicaxel no worries! Thanks for taking the time to contribute, and it's good to have that info about cypress.

**Comment by aslakhellesoy** [comment]
Sorry, I thought this was just adding documentation for existing `And` and `But` implementations. I should have verified that they actually exist.

Thanks for reverting.

**Pull request merged**
