### PR TITLE
remove ruby, legacy features, cucumber-tck

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros @samccone 

Remove ruby, legacy feature tests, and cucumber-tck submodule. 
Introduced a bunch of feature tests to take their place.

Happy to add more feature tests if you think something is missing

### CODE REVIEW

**Comment by charlierudolph** [comment]
Travis build time dropped down to 7 and half a minutes

**Comment by charlierudolph** [comment]
@jbpros please take a look as soon as you can. Would love to get this in as an undefined step snuck in on one of the recent merges.

**Comment by charlierudolph** [comment]
@jbpros no idea why this started failed on node 0.8. 
How do you feel about dropping support?
The last 0.8 release was June 2013 and with 3 newer versions (0.10, 0.12, and 4.0), 
I'd prefer to not have to worry about it.

**Comment by jbpros** [comment]
I'm happy to drop support for 0.8.

**Comment by samccone** [comment]
:+1:

**Comment by charlierudolph** [comment]
@jbpros this is now 3 weeks old. Unless you voice objections over the weekend, I am going to merge this on Monday

**Pull request closed without merging**
