### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [LGTM code quality badges](https://lgtm.com/projects/g/cucumber/cucumber-js/ci/#badges) to your project, to show how you care about code quality and encourage contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/cucumber/cucumber-js).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by charlierudolph** [comment]
Can you expand on what the benefit of using LGTM is? By looking at the basic set of alerts it appears to be similar to a linter that is preconfigured for you and works with whatever language. Based on the alerts reported it appears to go a bit further than other linters.

Writing custom queries seems very powerful but I don't know of something I would use that for currently. 

It gives two alerts for this repo which one I believe is a false positive and the other pointed out a small bit of code that can be deleted. Can you take a look at the first and let me know if that is a false positive? 

I would be good adding the alerts badge (I don't think we need the other).

**Comment by xcorail** [comment]
Hi @charlierudolph 

Thanks for the feedback!

> Based on the alerts reported it appears to go a bit further than other linters.

You got it right. Our technology compiles the code, extracts comprehensive data into a DB, then queries this DB. It allows us to do deeper analysis that other linters cannot do, such as complex data flow queries. 

> Writing custom queries seems very powerful but I don't know of something I would use that for currently.

I understand. The usage is usually like "I come across a bug by pure chance ... hey, let me write a query to check if there are other occurrences, or variants of this bug. And prevent it forever".  Have a look at this [post](https://blogs.technet.microsoft.com/srd/2018/08/16/vulnerability-hunting-with-semmle-ql-part-1/), to see real examples of how it's used at Microsoft. 

> Can you take a look at the first and let me know if that is a false positive?

Yes ... weird ... there must be something I miss here ... Let me bring that to the JS team! 

> I would be good adding the alerts badge (I don't think we need the other).

Will do! 

While I'm at it, some precisions about the runs:
* our recommended usage is to integrate LGTM with your Pull requests. LGTM will analyse immediately the PR, and report any new problem, or fix, directly within the PR. It's a [one-click operation](https://lgtm.com/projects/g/cucumber/cucumber-js/ci/)
* otherwise LGTM polls your repo once a day and analyses all commits, most recent first

Cheers

**Comment by xcorail** [comment]
Hi @charlierudolph 

About the first alert, I got an answer from my JS team. I was looking at the wrong problem. 
The alert message says : This does not backslash-escape **the backslash character**.
The problem is that it escapes quotes with backslashes, but it doesn't escape backslashes. If the input string contains `\'`, that will become `\\'`, which is presumably an escaped backslash followed by an unescaped quote 

I modified the PR to include only the alerts badge as you proposed.

**Comment by charlierudolph** [comment]
> About the first alert, I got an answer from my JS team. I was looking at the wrong problem.
The alert message says : This does not backslash-escape the backslash character.
The problem is that it escapes quotes with backslashes, but it doesn't escape backslashes. If the input string contains \', that will become \\', which is presumably an escaped backslash followed by an unescaped quote

Auhh. What is the suggested workaround for this? Not worried about an input attack in this case as the class is generating a snippet for the user and if in the worse case there is `\'` in the string then the user will get a compile error when they use the snippet.

**Comment by xcorail** [comment]
Hello @charlierudolph 
Apologies for not answering your latest comment for so long.

If you are in a code that is not security sensitive (and that will never be, and will never be used in another context in the future), then the solution is to suppress this alert in this particular code, by adding a `//LGTM` comment, as described in our [documentation](https://lgtm.com/help/lgtm/alert-suppression)

Let me know it that makes sense.

**Comment by charlierudolph** [comment]
Thanks for the PR but going to close as we already have a linter and don't really want to add additional comments to suppress alerts.

**Pull request closed without merging**
