### PR TITLE
switch from npm to yarn

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros 

My coworker introduced me to yarn and its amazing. Travis and appveyor support it out of the box

### CODE REVIEW

**Comment by charlierudolph** [comment]
Dropping support for node 0.12 with this as yarn requires node 4. Node 0.12 will no longer be maintained at the end of the year so I think thats okay.

**Comment by jbpros** [comment]
I've been using yarn for a while and it is amazing indeed. Way to go!

As a side note, I think it'd be good to add Node 7 to the travis build matrix, if that's possible.

**Comment by charlierudolph** [comment]
Sounds good

**Comment by jbpros** [comment]
SPEEEEEED! 🚄 🎉

**Pull request closed without merging**
