### PR TITLE
use commander for cli parsing

### LINKED ISSUE #433: replace bespoke argument parsing with a lib
In 2015 there is no need to roll our own any more  

Let's :fire: `lib/cucumber/cli/argument_parser.js`

Replace with:
https://github.com/bcoe/yargs

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros @samccone 

closes #433 

Moved some documentation from the help screen to the README as commander only allows the description of an option to be a single line.

### CODE REVIEW

**Comment by jbpros** [comment]
@charlierudolph @samccone: first off, can you guys explain why you think nopt has to go away?

Whatever your answer will be, I'm not married to nopt, it was great at the time but we can ditch it. I like how the codebase has shrunk and got simpler with this PR.

I'm not convinced by the reduced help output. There was important behaviour related to the CLI flags (`--require` is a good example) that has become less obvious to our users. I don't see how this is an improvement for them, on the contrary.

I see that commander lets you write [custom help](https://www.npmjs.com/package/commander#custom-help). Can we do that instead and restore the CLI documentation?

**Comment by charlierudolph** [comment]
nopt's negatives to me
* it ignores unknown options instead of throwing an error
* it supports [abbreviations](https://github.com/npm/nopt#abbreviations) which I think is just wrong
* it doesn't aid in the creation of help text

I'm fine adding a few examples to the custom help but I would prefer to keep the help screen short so its easier to navigate. Can you please make a list of the examples you would like in the custom help?

**Comment by samccone** [comment]
big one for me 

`it doesn't aid in the creation of help text`

:+1: this is so good @charlierudolph so much less code

**Comment by jbpros** [comment]
@charlierudolph alright, those are all good points. 

Describing the `--require` and `--tags` flags more thoroughly is important, imo. It's also annoying to lose the list of built-in formatters accepted by `--format`.

I hear you regarding the short help screen. What about we add specific help sections to mitigate the too-long default help screen (e.g. `cucumber.js --help format`)?

**Comment by charlierudolph** [comment]
@jbpros how do you feel about putting the more detailed descriptions in a man page? And adding a line to the CLI help screen directing them to the man page for more info?

**Comment by samccone** [comment]
> how do you feel about putting the more detailed descriptions in a man page? And adding a line to the CLI help screen directing them to the man page for more info?

+1 to this idea

**Comment by jbpros** [comment]
How would Windows users access the man page?

**Comment by samccone** [comment]
> descriptions in a man page

Could this be something like cucumber --help and it simply prints the "MAN" page to stdout?

**Comment by charlierudolph** [comment]
Windows has a [workaround](http://stackoverflow.com/questions/944434/where-is-the-man-program-for-windows-program-to-open-unix-man-pages) to view man pages.

**Comment by jbpros** [comment]
yeah I saw that SO question already. Seems fiddly for our users though.

**Comment by charlierudolph** [comment]
What's wrong with having the short documentation in the help screen and redirecting users to the README for now for additional explanation about the options?

**Comment by jbpros** [comment]
@charlierudolph ok, I agree. Let's keep things simple. Can you explicitly refer to the README and link to it on github from within the CLI help?

**Comment by jbpros** [comment]
Oh and let's not use a capital letter for the first character of the help strings. The builtin ones (version and help) start with a lowercase char.

**Pull request closed without merging**
