### PR TITLE
Verbose summary formatter

### PR DESCRIPTION
**Pull request by subhojit777**
This formatter is similar to summary formatter, plus it comes with the goodness of pretty formatter. Once a scenario is completed, it will show all the steps with their status. Once a feature has finished execution it will show the summary.

### CODE REVIEW

**Comment by charlierudolph** [comment]
Can you please add unit tests / a feature test for this so we can have an example of what is output?

**Comment by subhojit777** [comment]
I am still working on the tests. I'll update here once I am done.

**Comment by charlierudolph** [comment]
How exactly is this different from the pretty formatter?

**Comment by subhojit777** [comment]
Pretty formatter will give you live output of the steps. While this formatter will output the whole summary of every scenario.

For example:
```
Scenario: Test login form with correct credentials
  Given User is on login form
  When User enters username
  And    User enters password
  And    User clicks submit button
  Then  User should see welcome message
```

In pretty formatter, it will give you live output of every step. Like this:

```bash
Scenario: Test login form with correct credentials
  tick  Given User is on login form
  tick  When User enters username
  cross And    User enters password
```

While verbose summary formatter will output like this:

```bash
Scenario: Test login form with correct credentials
  tick    Given User is on login form
  tick    When User enters username
  cross   And    User enters password
  skipped And    User clicks submit button
  skipped Then  User should see welcome message
```

**Use case:**
This formatter is useful when you are running the feature files parallely, and the output gets mixed up, not able to distinguish which step belongs to which scenario.

**Comment by subhojit777** [comment]
Also I think the functions `formatTags`, `logIndented`, etc. are duplicate and they need to be moved to a helper class, so that both pretty formatter and verbose summary formatter can use them.

**Comment by subhojit777** [comment]
Verbose summary formatter combines the goodness of pretty formatter and summary formatter.

**Comment by charlierudolph** [comment]
Auhh, okay. Can you please create an issue for your use case and close this PR? I liked to discuss the use case further and am interested in how you are running cucumber in parallel. I would rather build in parallelism into cucumber-js and update the existing formatters to support that instead of having a dedicated formatter for parallel runs.

**Comment by mucsi96** [comment]
Hi @charlierudolph! I am very happy that you plan to add support for parallelism in cucumber-js. It would make [my package](http://mucsi96.github.io/nightwatch-cucumber/) much more easy. Can I help with the implementation of this feature?

**Pull request closed without merging**
