### PR TITLE
usage formatter

### LINKED ISSUE #468: Command For Finding Unused Steps in Codebase
Rails has a really handy command that looks through your codebase to find unused steps: `cucumber --dry-run -f stepdefs`. Would love to have that functionality available for cucumber-js as well.

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros 

@mattwynne I departed a bit from the cucumber-ruby usage formatter. I didn't think it was worth it to ever list every single match and instead listed only the slowest 5. Thus lets the user focus on bottlenecks and unused steps. What do you think of this?

resolves #468

### CODE REVIEW

**Comment by jbpros** [comment]
I like the idea of not overwhelming people with not-so-useful/useless data.

That said, I can think of use cases other than the one where you just want to immediately fix the slowest steps, other use cases where knowing the complete list of stepdef durations would be useful.

Could that be an option passed to the formatter (which, I'd be happy to default to 5, I think you have a valid point there about)?

BTW, I'm really looking forward to this feature! 💯

**Comment by mattwynne** [comment]
I know that quite few people use this formatter (in the  Ruby version) to show them the catalogue of step definitions that are available to use in their scenarios, particularly when using libraries like Aruba.

I think that's really a separate use-case to the one of trying to identify and speed up slow-running steps.

Perhaps they both deserve their own specialised formatter?

**Comment by charlierudolph** [comment]
@mattwynne @jbpros 

I do think the need to see every match it a separate use case and one that should have its own formatter. To me that use case is when you're feeding the usage into another system and thus we should be outputting json instead of something that is human readable.

Thoughts on having a `usage-json` formatter which gives the full data in json format?

**Comment by charlierudolph** [comment]
Added on a `usage-json` formatter to this PR which outputs the full data.
It outputs an array of objects with the following keys
* pattern
* line
* matches - array of objects
  * duration
  * line
  * text
  * uri
* meanDuration
* uri

duration / meanDuration are not present if in dry run mode
meanDuration is not present if there are no matches

**Comment by jbpros** [comment]
Nice one @charlierudolph! Thanks for adding the json formatter.

**Pull request closed without merging**
