### PR TITLE
Replace cli-table with cli-table2

### PR DESCRIPTION
**Pull request by honzajavorek**
The cli-table looks like an abandoned project and has licensing issues it is not willing to resolve:

- https://github.com/Automattic/cli-table/issues/93
- https://github.com/Automattic/cli-table/pull/101
- https://github.com/Automattic/cli-table/pull/68

According to https://github.com/Automattic/cli-table/pull/68#issuecomment-268793354 it is advised to use [cli-table2](https://github.com/jamestalmage/cli-table2/) instead. Moreover, that package has licensing all right.

Related to https://github.com/cucumber/cucumber-js/issues/1124

### CODE REVIEW

**Comment by honzajavorek** [comment]
Quoting the [cli-table2](https://github.com/jamestalmage/cli-table2/) README:

> This utility allows you to render unicode-aided tables on the command line from your node.js scripts. Based on (and api compatible with) the original cli-table, cli-table2 is nearly a complete rewrite to accommodate column and row spanning. It passes the entire original cli-table test suite, and should be a drop in replacement for nearly all users.

**Comment by charlierudolph** [comment]
Cool. I'll try to merge and make a release this weekend

**Comment by charlierudolph** [comment]
Have to note that there is also [cli-table3](https://github.com/cli-table/cli-table3) which claims cli-table2 is unmaintained. Don't think that matters currently for our usage.

**Comment by honzajavorek** [comment]
Oh, wow, I did not notice that. Hopefully there are not even more sequels
:))

Thank you for merging!

**Pull request merged**
