### PR TITLE
Use vanilla js for disable timeouts example

### PR DESCRIPTION
**Pull request by plocket**
Not sure if this needs any kind of version bump, etc. since it's just cucumberjs-specific documentation.

Replaces the current ['Disable timeouts' example](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md) that uses `bluebird` with an example using a vanilla js `Promise`. It clears the timeout to avoid the hang (took me ages to figure that out). It also shows doing operations after the promise resolves (with a warning).

Not sure this is the most simple example possible as I don't work with promises much, but this is what worked for me and gave me an meaningful understanding of how things work inside there. It could just be hindsight, but I think I would have found this code easier to use as a starting point from which I could build. As the project my team is doing doesn't need `bluebird` for anything else, it would also avoid digging into that library.

### CODE REVIEW

**Comment by charlierudolph** [comment]
I think this has a good example of a promise with timeout that we could add to the sample as a helper function.

https://spin.atomicobject.com/2020/01/16/timeout-promises-nodejs/


Then the sample step can just be
```js
const promiseWithTimeout = (timeoutMs, promise) => {
  /* helper method as outlined */
}

Given('the operation completes within {number} minutes', {timeout: -1}, async function(minutes) {
  const milliseconds = minutes * 60 * 1000
  
  // verifyOperationComplete returns a promise
  await promiseWithTimeout(milliseconds, this.verifyOperationComplete());
  
  // Do other stuff as long as it will also definitely finish
  console.log(`Everything from here on out has to finish as well.`);
})
```

**Comment by plocket** [comment]
I appreciate the simplicity of the code you present. It misses a bit of the point of my example. I'd like to actually show how to use the insides of a timeout to allow the process to exit properly. That's the part that I struggled with when dealing with this code - I needed to clear the timeout. Is there a way to simply the code while also showing that?

Separately, can you use `this` in that way in the context of `Given()`? That is, will `this` let you `Given()` the global scope in the script.

**Comment by charlierudolph** [comment]
> I appreciate the simplicity of the code you present. It misses a bit of the point of my example. I'd like to actually show how to use the insides of a timeout to allow the process to exit properly. That's the part that I struggled with when dealing with this code - I needed to clear the timeout. Is there a way to [simplify] the code while also showing that?

The second example on the article is:

```ts
const promiseWithTimeout = (timeoutMs: number, promise: () => Promise<any>) => { 
  let timeoutHandle: NodeJS.Timeout;
  const timeoutPromise = new Promise((resolve, reject) => {
    timeoutHandle = setTimeout(() => reject(), timeoutMs);
  };

  return Promise.race([ 
    promise(), 
    timeoutPromise, 
  ]).then((result) => {
    clearTimeout(timeoutHandle);
    return result;
  }); 
}
```
I'd say we could use that but probably also pass an error to the timeout reject call so it looks like
```ts
  let timeoutHandle: NodeJS.Timeout;
  const timeoutPromise = new Promise((resolve, reject) => {
    timeoutHandle = setTimeout(() => reject(new Error('Promise timed out')), timeoutMs);
  };
```

> Separately, can you use this in that way in the context of Given()? That is, will this let Given() [access] the global scope in the script.

`this` in hooks / steps is a world instance. See more [here](https://github.com/cucumber/cucumber-js/blob/v7.0.0/docs/support_files/world.md)

**Comment by plocket** [comment]
I'm not completely clear on everything you're suggesting. I find the code of `promiseWithTimeout` more complex and confusing that what I currently have. There are a lot more steps to trace to understand what's going on. It looks like it might have fewer lines, but there are so many more new functions and promises being created.

What I'm hoping to do here is have something as straightforward and direct as possible. If people can abstract it more in their code if they want.

Showing people how to abstract is a good goal, but I think putting that lesson here would be distracting. If you want, I can add a link to a new page that explains how to abstract in that way. Maybe another way to address it is to add that helper function to cucumber-js for people to use when they need to. I'm not sure that it fits into the current roadmap for cucumber-js, though.

The below is something that's slightly more abstracted than what's in my PR now. To me, it seems like it doesn't do what you want _and_ it doesn't do what I want, but I could be wrong. Does it do more of what you want?

```javascript
var {Given, When} = require('cucumber');

const myActionWithATimeout = async ( timeoutMins ) => {
  const custom_wait_time = timeoutMins * 60 * 1000;
  const promise = new Promise(function( resolve, reject ) {
    // Set up the timeout and get its id
    const custom_timeout = setTimeout(function() {
      throw `Operation did not complete within ${ timeoutMins } minutes.`;
    }, custom_wait_time );

    // Do your stuff inside a self-invoking anonymous async function
    (async function() {
      try {
        const result = await myAsyncStuff();
        resolve( result );
      } catch ( err ) {
        throw err;
      } finally {
        // prevent remaining timeout hang that could otherwise happen at end of tests
        clearTimeout( custom_timeout );
      }
    })();
  });
  
  return await promise;
};

When('the operation completes within {n} minutes', {timeout: -1}, async( minutes ) {
  const the_good_stuff = await myActionWithATimeout( minutes );
  // Do other stuff as long as it will also definitely finish
  console.log(`Everything from here on out has to finish as well.`);
});
```

**Comment by charlierudolph** [comment]
Created #1566 to expose the promise timeout helper cucumber-js use internally.

Overall don't think its worth cucumber-js to have a more detailed example of how promise timeouts can be implemented. There are plenty of other online resources that can be used.

**Comment by plocket** [comment]
Can there be a note added about how the timeout has to be destroyed if everything is resolved?

**Pull request closed without merging**
