### PR TITLE
Type tag with 'scenario' as value added to scenario element

### PR DESCRIPTION
**Pull request by szymonprz**
Hello,
I want to use jenkins to generate report from json file generated by JsonFormatter. We're using https://github.com/jenkinsci/cucumber-reports-plugin to generate cucumber reports on jenkins, but to do that "type" tag for scenario is required to identify element as scenario.

### CODE REVIEW

**Comment by charlierudolph** [comment]
Why is the type tag needed? Currently there is no other type of element exported via the JSON formatter

**Comment by szymonprz** [comment]
To distinguish scenario from background. Current json formatter should be compatible with json formatters for other cucumber implementations. The output from json formatter should be like here from relish json formatter https://relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter

**Comment by aslakhellesoy** [comment]
Hi @szymonprz,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for we ask you to:

* ✅ Please continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by charlierudolph** [comment]
Thanks!

**Comment by manu7691** [comment]
Is is possible to add this PR to v2 as well?

**Pull request merged**
