### PR TITLE
remove coffeescript/pogo dependencies in favor of CLI arguments

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros samccone

Following mocha's interface of defining a compiler to javascript with 
`--compiler <extension>:<moduleToRequire>`.

### CODE REVIEW

**Comment by charlierudolph** [comment]
I think #303 needs to go in before this to make the transition for those relying on this much easier.

**Comment by jbpros** [comment]
Almost ready to merge. Can you please document it in the README and CLI's `--help`?

**Comment by jbpros** [comment]
@charlierudolph thanks, I'm taking care of this now

**Comment by jbpros** [comment]
Thanks Charlie, this is really cool.

Merged in as dcdc32d

**Pull request closed without merging**
