### PR TITLE
debt: add retry for publish tests

### LINKED ISSUE #1457: Intermittent publish failures
Seen the following intermittently on CI:

```
1) Scenario: the publication banner is not shown when publication is done # features\publish.feature:114
   √ Before # features\support\hooks.ts:16
   √ Before # features\support\hooks.ts:20
   √ Given a report server is running on 'http://localhost:9987' # features\step_definitions\report_server_steps.ts:8
   √ And my env includes "CUCUMBER_PUBLISH_URL=http://localhost:9987/api/reports" # features\step_definitions\cli_steps.ts:15
   √ And a file named "features/a.feature" with: # features\step_definitions\file_steps.ts:10
       """
       Feature: a feature
         Scenario: a scenario
           Given a step
       """
   √ And a file named "features/step_definitions/steps.js" with: # features\step_definitions\file_steps.ts:10
       """
       const {Given} = require('@cucumber/cucumber')
       Given(/^a step$/, function() {})
       """
   √ When I run cucumber-js with arguments `--publish` and env `` # features\step_definitions\cli_steps.ts:29
   √ Then the error output does not contain the text: # features\step_definitions\cli_steps.ts:118
       """
       Share your Cucumber Report with your team at https://reports.cucumber.io
       """
   √ After # features\support\hooks.ts:110
   × After # features\support\hooks.ts:97
       Error: Last run errored unexpectedly. Output:
       .
       1 scenario (1 passed)
       1 step (1 passed)
       0m00.005s (executing steps: 0m00.000s)
       Error Output:
       ┌──────────────────────────────────────────────────────────────────────────┐
       │ View your Cucumber Report at:                                            │
       │ https://reports.cucumber.io/reports/f318d9ec-5a3d-4727-adec-bd7b69e2edd3 │
       │                                                                          │
       │ This report will self-destruct in 24h unless it is claimed or deleted.   │
       └──────────────────────────────────────────────────────────────────────────┘
       events.js:174
             throw er; // Unhandled 'error' event
             ^
       Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
           at ClientRequest.onclose (internal/streams/end-of-stream.js:57:15)
           at ClientRequest.emit (events.js:203:15)
           at Socket.socketCloseListener (_http_client.js:358:9)
           at Socket.emit (events.js:203:15)
           at TCP._handle.close (net.js:607:12)
       Emitted 'error' event at:
           at errorOrDestroy (internal/streams/destroy.js:107:12)
           at stream._final (_stream_writable.js:620:7)
           at sendRequest (C:\projects\cucumber-js\lib\formatter\http_stream.js:49:28)
           at stream_1.pipeline (C:\projects\cucumber-js\lib\formatter\http_stream.js:102:21)
           at internal/streams/pipeline.js:84:7
           at internal/util.js:370:14
           at ClientRequest.eos (internal/streams/pipeline.js:33:21)
           at ClientRequest.<anonymous> (internal/util.js:370:14)
           at ClientRequest.onclose (internal/streams/end-of-stream.js:58:23)
           at ClientRequest.emit (events.js:203:15)
           [... lines matching original stack trace ...]
           at TCP._handle.close (net.js:607:12)
           at World.<anonymous> (C:\projects\cucumber-js\features\support\hooks.ts:103:11)
```

### PR DESCRIPTION
**Pull request by davidjgoss**
Closes #1457.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Thanks @davidjgoss. Alas, Node 10 still fails, which reminds me: Node 10 [is no longer in LTS](https://nodejs.org/en/about/releases/), so how about we remove that from our CI? (could be done in this PR).

**Comment by davidjgoss** [comment]
@aslakhellesoy agree on dropping Node 10 but should that be a breaking change and therefore major release?

**Comment by aslakhellesoy** [comment]
Good question.

How about we just allow the CI to fail for Node 10, but still run it? That way we can keep support for CI without getting too distracted about the bugs in its http lib?

**Comment by aurelien-reeves** [comment]
I'm not sure the failed build is because of Node 10.

Why to use `--retry-tag-filter`? Will that be added to the filtering of the rerun file? Or override it?

**Comment by davidjgoss** [comment]
> I'm not sure the failed build is because of Node 10.

Yeah, I don't think it's exclusive to Node 10 either actually.

> Why to use `--retry-tag-filter`? Will that be added to the filtering of the rerun file? Or override it?

We aren't using the rerun file mechanism. The retry config I've added here means that, for pickles that have the `@flaky` tag, the test case will be retried up to twice (during the same test run).

**Comment by aurelien-reeves** [comment]
> > Why to use `--retry-tag-filter`? Will that be added to the filtering of the rerun file? Or override it?
> 
> We aren't using the rerun file mechanism. The retry config I've added here means that, for pickles that have the `@flaky` tag, the test case will be retried up to twice (during the same test run).

Ok, thanks for the details.

In our case, I would have tried for a rerun instead of a retry then - if I finally understand correctly the distinction between those 😅.
If there is something in the state of the HTTP server that is broken, a retry may not be sufficient to reset that broken state.

**Comment by davidjgoss** [comment]
I think we create a new instance of the fake http server for each test case? If so you would get a fresh one for each retry (we discard any state from the failed run and create a new world etc)

**Comment by aurelien-reeves** [comment]
> 
> 
> I think we create a new instance of the fake http server for each test case? If so you would get a fresh one for each retry 

Yes, we have a new instance of the http server for each test case.
But as we not understand what is happening when it is failing, I think we cannot really trust the internal state of what is related to that http server at some point.

**Comment by davidjgoss** [comment]
I don't think I'm quite grasping what the issue is with retry, but at any rate if we're against retry then what are we for (Besides fixing the actual issue.)

**Comment by aurelien-reeves** [comment]
I just noticed: the failed build here is not a cucumber test, but a mocha test, so it has even not been retried as the impacted suite was not the one we expected

I took a look on past builds, it happens very, very occasionally.

**Comment by aurelien-reeves** [comment]
It worked as expected this time:

```
Warnings:

1) Scenario: a banner is displayed after publication (attempt 1, retried) # features\publish.feature:76
   (...)
       1 scenario (1 passed)
       1 step (1 passed)
       0m00.005s (executing steps: 0m00.001s)


       Error Output:

       ┌──────────────────────────────────────────────────────────────────────────┐
       │ View your Cucumber Report at:                                            │
       │ https://reports.cucumber.io/reports/f318d9ec-5a3d-4727-adec-bd7b69e2edd3 │
       │                                                                          │
       │ This report will self-destruct in 24h unless it is claimed or deleted.   │
       └──────────────────────────────────────────────────────────────────────────┘

       Premature close

           at World.<anonymous> (D:\a\cucumber-js\cucumber-js\features\support\hooks.ts:107:11)
           at process._tickCallback (internal/process/next_tick.js:68:7)

266 scenarios (266 passed)
...
```

**Pull request merged**
