### PR TITLE
Upgrade to cucumber-expressions 4.0.0

### PR DESCRIPTION
**Pull request by aslakhellesoy**
This PR upgrades to [Cucumber Expressions 4.0.0](https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/CHANGELOG.md#400---2017-06-27)

There are backwards incompatible changes in this release, which might warrant a major version bump in cucumber-js too:

## Parameter types must be defined

Using an `{undefined}` parameter type will result in an error. This may sound like a hassle, but the benefits outweigh the drawbacks in my opinion.

Forcing users to define parameter types encourages the evolution of a ubiquitous language.

## New `{word}` and `{string}` parameter types

The `{word}` type is handy to use instead of old `{undefined}` ones.
The `{string}` type replaces the old `{stringInDoubleQuotes}` one, and works with both single and double quotes

## Parameter types can use the same regex

This used to cause errors in previous releases. Because they are now allowed, each undefined step
can result in several possible cucumber expressions for snippets, as outlined in https://github.com/cucumber/cucumber/issues/132.

For this reason, the `CucumberExpressionGenerator.generateExpression` method is deprecated in favour of `CucumberExpressionGenerator.generateExpressions`, which returns a list of `GeneratedExpression` (the one at index 0 is the one the user is most likely to want).

So before this PR is merged, it should be updated to use the new method, and display all expressions when printing snippets. As discussed with @charlierudolph at cukeup, we're not sure how to best do that. Let's discuss some possible output examples in this issue before proceeding.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Looks like it [fails](https://travis-ci.org/cucumber/cucumber-js/builds/248169634?utm_source=github_status&utm_medium=notification) because cucumber-expressions uses [Array.includes](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) which isn't supported on Node 4 (and IE).

Do you think I should replace it with something more widely supported?

**Comment by charlierudolph** [comment]
Please use [lodash.includes](https://lodash.com/docs/4.17.4#includes) for now

**Comment by aslakhellesoy** [comment]
I'm trying to depend on as few libs as possible in cucumber-expressions, will probably just do `indexOf`

**Comment by aslakhellesoy** [comment]
While you're waiting for me to release a new cucumber-expressions, would you consider improving this PR to print multiple expressions in snippets?

**Comment by charlierudolph** [comment]
Sure. My initial thought for a snippet from multiple expressions would be the following:
```javascript
Given('<expr1>', function() {
  // Other matching expressions
  //  <expr2>
  //  <expr3>
  
  // Write code here to 
})
```

**Comment by aslakhellesoy** [comment]
That could work. Have you thought about displaying the function parameters in addition to the expression? I think it will be tedious and error-prone to have to have to come up with them.

**Comment by charlierudolph** [comment]
Okay so something like
```
Given('<expr1>', function(abc, def) {
  // Other matching expressions
  //  Given('<expr2>', function(ghi, jhk) {
  //  Given('<expr3>', function(lmn, opq) {
  
  // Write code here to 
})

**Comment by aslakhellesoy** [comment]
In https://github.com/cucumber/cucumber-ruby/pull/1156 (Cucumber Expression in Cucumber Ruby) I decided to print snippets with multiple possible expressions like so:

```ruby
Given("I have {float} {cucumis} in my belly") do |float, cucumis|
# Given("I have {float} {veg} in my belly") do |float, veg|
  pending # Write code here that turns the phrase above into concrete actions
end
```

We should follow the same convention in Cucumber.js

**Comment by charlierudolph** [comment]
Sounds good to me

**Comment by charlierudolph** [comment]
@aslakhellesoy any update on making cucumber-expressions support node 4? I have a few other breaking changes about to land and would be good to get this in with them

**Comment by charlierudolph** [comment]
@aslakhellesoy bump. I'm just about ready to release cucumber-js 3.0 and since this has breaking changes it will need to wait for a major release. Do you think you have time to support node 4 or want some help? I can implement the updated snippets.

**Comment by aslakhellesoy** [comment]
I think the latest cucumber-expressions release fixes the Node 4 issues. Could you try to update the PR to use that? Am on holiday and won't be near a laptop for 10 days or so.

**Comment by charlierudolph** [comment]
Sounds good thanks.

**Comment by aslakhellesoy** [comment]
Wohooo can't wait to use this. Thanks @charlierudolph 💥

**Pull request merged**
