### PR TITLE
Refactor exit flow to limit forceful termination

### PR DESCRIPTION
**Pull request by kozhevnikov**
Implements #889

### CODE REVIEW

**Comment by kozhevnikov** [comment]
It still forcefully terminates if anything hangs but now allows for few seconds (same as default timeout) to exist gracefully by itself (`unref` makes event loop ignore the pending timeout). If it's still running after 5 seconds the process is terminated just as before.

**Comment by charlierudolph** [comment]
I don't like the 5 seconds delay for those that don't need it though. I would prefer as discussed in the issue as it retains current speedy behavior and allows for waiting for the event loop to close. The 5 second delay is a weird middle ground to me

**Comment by kozhevnikov** [comment]
The delay is only for when bad things have happened, something have hung and somehow blocked cucumber/node from exiting on its own. The problem with having a binary choice between exit or drain is that in normal day to day operation I need a second for flush to be completed after cucumber have exited but node still have something in the event loop (e.g. file logger hasn't finished writing to file and missing important debug messages). If everything is fine then there's no delay, cucumber exists, buffer is flushed momentarily, node exists, all done, timeout is never triggered and discarded thanks to unref. If something unexpected does happen and node is stuck using drain argument would result is stuck CI builds. Having this failsafe makes cucumber behave the same as before in 99.999%  cases while allowing for error to be logged and written and the node process still terminated forcefully in case where event loop cannot be drained by itself gracefully. It's not a middle ground but rather all encompassing fix.

**Comment by charlierudolph** [comment]
> file logger hasn't finished writing to file and missing important debug messages

Why is that handled async outside of cucumber? Could this be updated so cucumber can wait for it to finish or in a separate process so its not reliant on when cucumber exits?

> It's not a middle ground but rather all encompassing fix.

I could see this delay not being enough for someone and thus having them ask for it to be bumped. Making the delay user configurable would be a better solution than the hardcoded 5 seconds but the use case you described makes me think this can be solved in a more reliable way

**Comment by kozhevnikov** [comment]
I agree, 5 seconds is completely arbitrary, I used the default cucumber step timeout value. Whoever would want to increase it later on can make it configurable and submit a new PR. I my case 100ms is enough to flush file buffers but since it doesn't actually wait for the timeout to fire (unless it's hung) it makes no difference for performance if it's 100ms or 5s.

It's normal for logging libraries (i.e. winston, bunyan, etc). Calling write queues up message event for logging and multiple transport plugins process it, i.e. stdout transport is sync while file transport is async and any logging SaaS transport is async and slow but those typically have their own dedicated process that manages the queue and retries and delays of remote calls.

**Comment by charlierudolph** [comment]
For the use case of logging libraries, I expect them to have a close or flush that you can add to a hook so that cucumber waits for them to finish. I really don't like adding waits to alleviate a timing issue instead of preventing the timing issue.

**Comment by charlierudolph** [comment]
I consider requirement 1 and 2 to be competing with each other. The flag to switch between exit and exitCode is so that we can satisfy both requirements at different times. I'd prefer we do something similar to `mocha` which introduced a `--no-exit` flag which set the exit code and let the loop drain. In the next major version they made that the  default, and required you to opt in to exiting immediately.

I consider this PR the step after the `--no-exit` flag, if we find that its not good enough. I prefer we try what I believe is a simpler solution first (and one used in another project bigger than this), as I don't think the delayed exit is not needed.

**Comment by charlierudolph** [comment]
See https://github.com/mochajs/mocha/issues/1855 for an interesting idea of an extension to the `--no-exit/--exit` flag where the user wants it to error if the event loop doesn't drain. I think we need the simple solution of drain the event loop or not first and then can revisit the delay down the line as needed.

**Pull request closed without merging**
