### PR TITLE
Allow Cucumber to load custom formatter

### PR DESCRIPTION
**Pull request by afternoon**
@joshtombs PR #215 + the requested additional tests.

### CODE REVIEW

**Comment by mojjj** [comment]
any news on this -.- ?

**Comment by stjohnjohnson** [comment]
Any updates here?

**Comment by paulreeve** [comment]
:+1:

**Comment by stjohnjohnson** [comment]
@afternoon @paulreeve @samccone what can I do to help get this merged?

**Comment by samccone** [comment]
heh looks like we need a rebase, I was just waiting on the :+1: from @jbpros

**Comment by stjohnjohnson** [comment]
@afternoon can you rebase this?

**Comment by samccone** [comment]
See #309

**Pull request closed without merging**
