### PR TITLE
rework error reporting

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros @mattwynne @aslakhellesoy 

### Old
screen shot 2016-02-24 at 10 48 41 pm

### New
screen shot 2016-02-24 at 10 18 52 pm

### Notes
* In the pretty formatter, errors are no longer printed beneath the failing steps but instead only printed in the summary. Having to scroll back through a possibly large output searching for the error is very annoying.
* Removed `--no-source` as the source is no longer printed on the pretty output as errors are no longer printed in it.
* Removed `--no-snippets` as snippets are always printed.

### CODE REVIEW

**Comment by kevgo** [comment]
+1 on summarizing the errors and warnings at the end! This is a big step forward in usability! Some thoughts while looking at this:

1. I'm not sure the errors and warnings need to be numbered. I think it would read equally nicely without them.

2. What do you think about highlighting the scenario and step names in a different color, to make locating them easier? Maybe blue?
`<black>Step: </black><blue>And a failing step</blue>     <gray>features/a.feature#8</gray>`

3. What about omitting the string "Message:" altogether? At least in your screenshot the actual error or warning message content makes it abundantly clear that this is the error message, especially together with the fact that it is printed in one of the error colors.

4. I would find it helpful for copy-and-pasting the snippet if it would remain separated from the rest of the output via an empty line above and below it. 

5. I'm not sure the headers ("Failures:", "Warnings") add much. I think this output would be equally usable if they were omitted. The type of issue is already encoded by the color of the message, I assume most people will use that as the cue what they are looking at, instead of those headings.

**Comment by charlierudolph** [comment]
1. I like the numbers for separation. I think it would be harder to look at it without numbers.

2. I'd prefer not to add another color. What about just bolding the label?

3. I don't know of any good way to format it without the `Message:` label. I don't like the look of just removing that line. We also need to consider the case where the user disables color.

4. That sounds good.

5. I think we need the separation as failures will cause an exit status of 1, and warnings will only cause an exit status of 1 if using the `--strict` flag, and otherwise don't effect the exit status. Again, in the case the user disables colors it'd be harder to tell. The headers may need to be changed to make them more prominent though.

**Comment by kevgo** [comment]
Re (2): I would bolden the content, not the label. The content is what you want the users to look at, the label just provides some (optional) metadata for it. Alternatively dim the labels, similar to how the file path after them is dimmed.

Re (3): I think at least in the examples you posted, it would look okay without the "Message:" label, even without colors. This is debatable though, both ways work here.

Re (5): I would like to keep a list of the failing scenarios, in a way so that the user can copy-and-paste the filename plus line number to run them (see "Failing scenarios:" in the old output). This is very useful to run particular scenarios on their own in order to fix them. It is also pretty standard, for example Mocha does the same. With that output back, there would be a list of failing scenarios, which would satisfy your requirement to make clear what exactly caused the Cucumber run to fail. Which then gives us the freedom omit the "Failures:" and "Warnings:" headers.

**Comment by mattwynne** [comment]
Is there any indication (other than colour) in the pretty output that a step has failed? I just wonder how people who can't see colour for any reason would interpret the output if that's the case.

I may have misunderstood but the source lines in the pretty output are often used to help people know where the step def for a step is. Are you saying that's gone now?

**Comment by mattwynne** [comment]
Oh and otherwise, thanks for innovating and cleaning things up @charlierudolph - I'd like to copy what you've done here for Ruby once we've stabilised on precise requirements everyone's happy with.

**Comment by charlierudolph** [comment]
> Is there any indication (other than colour) in the pretty output that a step has failed? 

Nope. But there also isn't anyway to tell pending / undefined / skipped steps either. I think this should be addressed separately.

> I may have misunderstood but the source lines in the pretty output are often used to help people know where the step def for a step is. Are you saying that's gone now?

Yes. I removed that as the step definition location is now listed as in the error/warning summary. To me the pretty output is just one way of printing the progress of the test run. I want the error/warning summary to contain all the data the user needs so they don't need to look back through the pretty output. I'm fine adding it back in, I just don't think its necessary.

As a side note: I personally don't use the pretty output anymore as for projects with a lot of features its just so much output to scan through. I use it currently for running single scenarios because our error summary isn't good enough. With this PR, I hope to change that.

**Comment by charlierudolph** [comment]
@kevgo here is the updated look with the bold scenario name / step text. I definitely do like that.

screen shot 2016-03-07 at 9 48 32 pm

@mattwynne any more comments?

**Comment by kevgo** [comment]
Looks great! I'd like to re-iterate the usefulness of summarizing the failures at the bottom, in a format that allows to run each one via simple copy-and-paste into a terminal. With the proposed formatter, I would have to scroll around to find the correct "Scenario" line, copy the parts after the scenario name, manually type "cucumber-js ", and then paste the file path in. Plus, these paths are a bit all over the place. A concise summary at the end, after the more detailed error messages, would add value in my opinion.

```
Failing scenarios:
cucumber-js features/a.feature:6
cucumber-js features/a.feature:11

Scenarios with undefined steps:
cucumber-js features/a.feature: 16

Scenarios with pending steps:
cucumber-js features/a.feature:21

**Comment by charlierudolph** [comment]
@kevgo I'd prefer to handle that as a separate formatter. If the main interest is just to run each failed scenario individually, I don't see any reason to output the detailed error messages. I'd be fine adding in a line to each error/warning block to give the command that can be copied and pasted, but I'd prefer not to separate it.

**Comment by kevgo** [comment]
I'm fine with any solution that allows me to see both outputs at the same time. (A) the details to get a quick overview of what errors have occurred (and infer what might be the root cause), as well as (B) a list of failures that allows me to re-run a spec that reproduces the root cause. 

I think having both types of information is useful, even if it is a bit redundant, considering that different people look for different things here. So, providing both types of information would make for a great new standard formatter for Cucumber.JS, that caters to many different people.

If you want to implement these two aspects as separate formatters, and Cucumber.JS allows me to run both at the same time, that would also be acceptable for my use cases here, since I know how to customize Cucumber, and have to do that on every project anyways. The only concern would be that a large fraction of your users will have to make this configuration change. But this call is up to the Cucumber team to make, not me.

**Comment by kevgo** [comment]
Looking at this again, what do you think about adding back the empty line that separates the snippet template for implementing missing steps from the associated error message? I.e. make it look like below, with line 3 being an empty line now:

```
Message:
  Undefined. Implement with the following steps:

    this.Given(/^an undefined step$/, function(callback) {
      ...
    });
```

**Comment by jbpros** [comment]
Yeah the blank line before the code block is better, in my subjective opinion ;)

**Comment by charlierudolph** [comment]
sounds good

**Pull request closed without merging**
