### PR TITLE
Attempt to fix workflow requiring node-15

### PR DESCRIPTION
**Pull request by aurelien-reeves**

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
From where that `Required` badge comes from!? 🤔
If we find how to remove it, or move it to another build, that should fix the issue

**Comment by aurelien-reeves** [comment]
Found it!
It is in the repository settings => branches => branch protection rules => [edit] the main branch

**Comment by davidjgoss** [comment]
Nice one @aurelien-reeves!

**Comment by charlierudolph** [comment]
Nice! I had messaged support about this as I couldn't find the config and they pointed to the branch protection rules. Sorry hadn't applied that yet.

**Comment by aurelien-reeves** [comment]
@charlierudolph  no worries, that was fun to dig into this :D

**Pull request closed without merging**
