### PR TITLE
remove use of domain

### LINKED ISSUE #394: Error handling after Node update.
I am using cucumber-js with selenium-webdriver and after updating Node from v0.10.29 to v0.12.7 node process crash on second error
``` js
c:\Users\user\dev\tests\node_modules\selenium-webdriver\lib\goog\async\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
```
Do you have any ideas why this could happen?

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros 

* node 0.8: Experimential
* node 0.10: Unstable
* node 0.12: Unstable
* node 4.0: Deprecated

Probably best to only bring this back when it becomes stable

fixes #394

### CODE REVIEW

**Comment by jbpros** [comment]
I'm all for removing the use of domains but I guess protractor/webdriver users are back to square one regarding exception handling.

@jlin412 would you be able to try it with protractor and if it fixes #394?

**Comment by jlin412** [comment]
Sure, is the change merged in the latest build?  Or I have to pull it from
Charlie's branch?

**Comment by jbpros** [comment]
@jlin412 from charlie's branch please :)

**Comment by jlin412** [comment]
Ok, I test with this branch: "cucumber": "git+https://github.com/cucumber/cucumber-js.git#cr-removeDomain";

Now, it is exited right away if there are two protractor promises and one of them are failing in a step vs it fails at the second time calling it previously.  I tested with the latest node 4.1.2.  I can provide some mini test case soon. 

Also, it worths mention, new timeout feature introduces some weird timeout error.  I can provide some test case as well.

**Comment by jbpros** [comment]
@jlin412 yes, please share a test case for this.

**Comment by jlin412** [comment]
@jbpros and @charlierudolph Here is branch that I am testing with https://github.com/jlin412/cuke-tractor
Just use the master.

Here is current error msg:
/Users/linj/cuke-tractor/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
NoSuchElementError: No element found using locator: By.cssSelector(".overlay")
    at new bot.Error (/Users/linj/cuke-tractor/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at /Users/linj/cuke-tractor/node_modules/protractor/lib/element.js:694:15
    at [object Object].promise.ControlFlow.runInFrame_ (/Users/linj/cuke-tractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at [object Object].goog.defineClass.notify (/Users/linj/cuke-tractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at [object Object].promise.Promise.notify_ (/Users/linj/cuke-tractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at [object Object].promise.Promise.notifyAll_ (/Users/linj/cuke-tractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (/Users/linj/cuke-tractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
    at process._tickCallback (node.js:357:9)
Error
    at [object Object].ElementArrayFinder.applyAction_ (/Users/linj/cuke-tractor/node_modules/protractor/lib/element.js:392:21)
    at [object Object].self.(anonymous function) [as isDisplayed] (/Users/linj/cuke-tractor/node_modules/protractor/lib/element.js:76:19)
    at [object Object].self.(anonymous function) [as isDisplayed] (/Users/linj/cuke-tractor/node_modules/protractor/lib/element.js:721:11)
    at World.<anonymous> (/Users/linj/cuke-tractor/features/step_definitions.js:16:19)
From: Task: <anonymous>
    at [object Object].Protractor.get (/Users/linj/cuke-tractor/node_modules/protractor/lib/protractor.js:692:29)
    at World.<anonymous> (/Users/linj/cuke-tractor/features/step_definitions.js:32:20)
[launcher] Process exited with error code 1

**Comment by charlierudolph** [comment]
Does `$('.overlay').isDisplayed()` return a promise? If so shouldn't the step at https://github.com/jlin412/cuke-tractor/blob/master/features/step_definitions.js#L15 be
```javascript
$('.overlay').isDisplayed().then(function() {
  $('.overlay').isPresent();
});
```

**Comment by jlin412** [comment]
Yes, $('.overlay').isDisplayed() and $('.overlay').isPresent() both returns promises.
However, protractor/webdriver.js internally has an internal control flow mechanism that can synchronize promises called by protractor.  https://github.com/angular/protractor/blob/master/docs/control-flow.md
We have checked mocha/jasmine versions of protractor and the same syntax works in there.

**Comment by jbpros** [comment]
@jlin412 can you add a working example with mocha or jasmine?

**Comment by charlierudolph** [comment]
@jlin412 bump. I believe this PR is waiting for more feedback from you

**Comment by jlin412** [comment]
@charlierudolph I apologize and fighting for prod issue last few days.  I update https://github.com/jlin412/cuke-tractor with a jasmine example.  As expected, it is working for jasmine2.
you will have to run node_modules/protractor/bin/protractor jasmine.conf.js
Let me know if you have any question.

**Comment by charlierudolph** [comment]
Alright so looking at that example ran into a whole host of different issues:

The master branch of cucumber-js already has a few breaking changes that cause issues.

Then there are step definitions also has some areas where a function throws an error outside of when its expected to (ie a synchronous step that sets a timeout to throw an error)

Finally, the real problem we run into is that there is already a listener for process.on('uncaughtException')  added via source-map-support (a dependency of protractor), which exits after printing the error. Thankfully source-map-support updated their handler to not exit if there are other listeners on uncaughtException. Thus once protractor updates its source-map-support, this issue should be resolved.

**Comment by jlin412** [comment]
@charlierudolph Thank your for troubleshooting at this issue.  Do you know if protractor plan to upgrade source-map-support or we need to bring it out to protractor community?  What version does it need?

**Comment by jbpros** [comment]
@charlierudolph brilliant! Nice catch with the uncaughtException handler. Can we do anything with regards to updating source-map-support in protractor?

**Comment by charlierudolph** [comment]
I opened a PR to that effect. angular/protractor#2615

**Comment by jbpros** [comment]
Sweet! Ta.

**Comment by charlierudolph** [comment]
@jbpros are you okay with merging this?

**Comment by jbpros** [comment]
@charlierudolph yes, please!

**Comment by bricas** [comment]
FWIW, I've tested this branch with my project and node v4.2.1 and it seems to fix #394 -- the second error now comes through as expected.

Is there a chance this would get merged and released sooner than 1.0?

**Pull request closed without merging**
