### PR TITLE
add CLI option to fail fast

### LINKED ISSUE #166: cli: bail or stop on failure flag
Hello Everyone,

thank you for writing cucumber-js, its really awesome.

I have a simple feature request and wondering what you've think about it. Would it be possible to add a "bail" or "stop on failure" flag to the cli? This changes the behaviour from cucumber to stop executing when the first scenario fails. In mocha its called "--bail" or "-b" in phpunit its "--stop-on-failure"

This comes handy if you have more than one scenario in one feature file and you just want to debug the first one. Or at least not all 7 if the first is always failing and youre fiddleing around to make it work.

best regards
Philipp

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros @samccone 

resolves #166

### CODE REVIEW

**Comment by jbpros** [comment]
Should we mention the suite was halted because of the fail fast mode, in the output?

**Comment by charlierudolph** [comment]
I don't really think thats necessary.

**Comment by jbpros** [comment]
Me neither, just challenging the idea.

LGTM

**Comment by jbpros** [comment]
Thank you @charlierudolph!

**Pull request closed without merging**
