### PR TITLE
Unit test for CLI flag --name + doc update

### PR DESCRIPTION
**Pull request by kamolins**
~~Addresses: #1309~~ 

- Added unit test to ensure that CLi flag --name supports regex
- Updated docs

### CODE REVIEW

**Comment by davidjgoss** [comment]
Thanks for doing this @kamolins, looks good.

Would you be able to add a test that fails without your change and passes with it?

**Comment by kamolins** [comment]
@davidjgoss Done!

**Comment by davidjgoss** [comment]
@kamolins sorry, looking again at [the documentation](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#running-specific-features), this argument is listed as supporting regular expressions, so moving away from `match` will break that which I don't think we want to do.

You should be able to escape the parentheses and other characters that have regex meaning with backslashes, I think?

I do still think there is worthwhile change to make here if you wanted to pivot this PR a bit:
- The doc briefly mention regex, but it might be worth showing an example with escaping
- No tests broke when you changed from `match` to `include` - we should add one that proves the regex support

**Comment by kamolins** [comment]
@davidjgoss You make a good point! `includes` won't match a regex, afaik. I should have read the docs more carefully. I will update the PR.

**Comment by kamolins** [comment]
@davidjgoss Updated the PR. Lmk if I should do anything else.

By the way, my previous push was marked as failed [here](https://ci.appveyor.com/project/charlierudolph/cucumber-js/builds/35585358/job/srgvx68bv6249r2e) on node v10 with an unrelated issue. Not really sure what went wrong there.

**Review by davidjgoss — APPROVED** [review]

**Comment by aslakhellesoy** [comment]
Hi @kamolins,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
