### PR TITLE
Replace 1 instance of regex with cucumber expression

### PR DESCRIPTION
**Pull request by karlajusten**
# Description

We started the process of replacing regex with cucumber expressions

# Motivation & context

It's one step towards fixing the issue #1871

## Type of change

- Refactoring/debt (improvement to code design or tooling without changing behaviour)

# Checklist:

- [ x ] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [ x ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
Hi @karlajusten, @blaisep, @Dparchmentjr, @mattwynne 

I guess this has been submitted as part of an ensemble and is still in progress?

Do you mind if I convert it to a draft PR?

**Comment by blaisep** [comment]
@aurelien-reeves , I think by the end of session, we determined that this represented an example of a minimum viable PR.
`IMHO` , it is OK if you roll this back to a draft, particularly if it helps clarify the criteria for transition from `draft` to `PR`.


> Hi @karlajusten, @blaisep, @Dparchmentjr, @mattwynne
> 
> I guess this has been submitted as part of an ensemble and is still in progress?
> 
> Do you mind if I convert it to a draft PR?

**Comment by aurelien-reeves** [comment]
> @aurelien-reeves , I think by the end of session, we determined that this represented an example of a minimum viable PR.

Yeah, it looks a viable PR.
But is it ready to be reviewed and then merged? Or do you plan to work more on that to replace more regexp with cucumber-expressions as part of this?

**Comment by aurelien-reeves** [comment]
The CI was failing because of linting issues. 
I allowed myself to fix those, I hope you don't mind!?

**Review by davidjgoss — APPROVED** [review]
Thanks for this, great start.

**Comment by aslakhellesoy** [comment]
Hi @karlajusten,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by karlajusten** [comment]
Thank you @aurelien-reeves for fixing the linting issues. And merging my first PR.

And thank you @aslakhellesoy  for welcoming me.

**Comment by aurelien-reeves** [comment]
@karlajusten you are very welcome :)

**Pull request merged**
