### PR TITLE
refactor: statuses

### PR DESCRIPTION
**Pull request by charlierudolph**
@jbpros 

Refactored the code around the status. Dropped the source code by about 300 lines
- Instead of classes for each type of step result, use one class with a `status` method.
- Introduce Runtime.ScenarioResult object to handle the logic of whether or not the scenario succeeded

Interface changes
- Api.Scenario
  - remove all the `is*` methods in favor of `getStatus`
- Summary Formatter
  - don't count hidden step results (hooks) as steps
- Progress Formatter
  - don't print a character for hidden step results (hooks) unless they fail.

### CODE REVIEW

**Comment by jbpros** [comment]
Nice one!

Removing the is* methods on the API scenario objects is a non-backward compatible change. I think it's nice to have it on the API so that end-users don't necessarily have to compare strings to check for specific states, which is a common thing they do:

    if (scenario.isFailed()) { ...

Is better than

    if (scenario.getStatus() == 'failed') { ...

Or even

    if (scenario.getStatus() == Cucumber.Status.Failed) { ...

**Comment by charlierudolph** [comment]
Okay. I'm fine putting those back on API.Scenario. Note that only one can be true as previously multiple could be true.

**Comment by charlierudolph** [comment]
@jbpros updated

**Comment by jbpros** [comment]
:+1:

All those PRs are going to reduce the browserified bundle a bit ;)

**Pull request closed without merging**
