### PR TITLE
browserstack integration

### PR DESCRIPTION
**Pull request by nidhimj22**
Cucumber tests can be run on BrowserStack infrastructure out of the box.
Attached link for sample repo in the README.md

### CODE REVIEW

**Comment by charlierudolph** [comment]
Cool. I'd like the following points addressed in that repo before merging this in:

* package.json 
  * Using old version of cucumber-js, please update to the latest
* README
  * Configuration instruction BS_USERNAME appears twice, one should be BS_ACCESS_KEY
* features/support/hooks.js
  * In After hook, when the scenario has failed, you aren't waiting for the screenshot to actually be written before executing the callback. Thus cucumber-js may exit before it is actually written.
  * In AfterFeatures handler, you aren't waiting for the driver to actually exit, cucumber-js may exit before it is actually quits

**Comment by nidhimj22** [comment]
@charlierudolph I have made the changes in that repo. 
Please merge this PR in case it looks good to you.

**Comment by nidhimj22** [comment]
I noticed all examples are removed from the README. So this PR now makes no sense. Let me know in case you have moved the examples to some other locations or else close the PR if they are completely removed from this main cucumber-js repo.

**Comment by charlierudolph** [comment]
Appears we removed the examples, so closing.

**Pull request closed without merging**
