### PR TITLE
Chore: Add time when gen formatter json to check timing between features

### PR DESCRIPTION
**Pull request by vctqs1**
# Description
Add time into interface `IJsonFeature` to can received actual test run time

# Motivation & context
I try to generate a report site from JSON file and I need time running test of feature files to sort which run first

## Type of change

- Refactoring/debt (improvement to code design or tooling without changing behaviour)
[_Remember to add an entry to the relevant section of CHANGELOG.md as part of this pull request._](https://github.com/cucumber/cucumber-js/pull/1784/commits/cc3d979d419fd275e72c59a95261f1d8cc3cb044#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL1849-R1851)

## Note to other contributors
- No impact

## Update required of cucumber.io/docs
- No impact

# Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
Hi,

Thanks for your contribution.

> I try to generate a report site from JSON file and I need time running test of feature files to sort which run first

Is this your only need? If so, please note that reports shows the test in the execution order. You don't need extra data to deduce that.

I encourage you to use your own custom formatter based on the internal formatters.

Also, did you take a look on the "messages" formatter? The json formatter is legacy. The "messages" are more modern and may be more efficient to process.

**Comment by vctqs1** [comment]
> I encourage you to use your own custom formatter based on the internal formatters rather than extending the internal json formatter.

Thanks for replying @aurelien-reeves 

Hi we already building a report side based on JSON fomatter and using random order option. So team want to add more information about timming to help metric and monitoring test cases better

**Comment by aurelien-reeves** [comment]
> Hi we already building a report side based on JSON fomatter and using random order option. So team want to add more information about timming to help metric and monitoring test cases better.
> 
> This help too much for comparing with logs in Backend site and tracking time between setup steps

Ok. Thanks for the details.
Still, I think it will be better for you to extend the JSON formatter into a dedicated custom formatter with the info you need.

I am not sure we will accept your pull request as it would impact everyone to covers your specific needs. With a custom formatter, you'll be free to do whatever you want, and to use it with your reporting service.

**Comment by vctqs1** [comment]
> Ok. Thanks for the details.
> Still, I think it will be better for you to extend the JSON formatter into a dedicated custom formatter with the info you need. Also we have put the JSON formatter into maintenance mode: we may not accept enhancement for that formatter.
> 
> I am not sure we will accept your pull request as it would impact everyone to covers your specific needs. With a custom formatter, you'll be free to do whatever you want, and to use it with your reporting service.


Thanks for your point out, But can I  ask why JSON formatter is legacy.

My team can write a custom formatter extends from JSON formatter but better if we can know reason why JSON formatter is legacy

**Comment by aurelien-reeves** [comment]
Because all cucumber implementation did not had the same json structure. So a new common protocol has been created: messages.

Messages can be reported as ndjson, and that protocol is shared across all implementations. Some tooling exists to convert ndjson messages into a json that looks pretty close to the legacy json formatters.

**Comment by aurelien-reeves** [comment]
Because all cucumber implementation did not had the same json structure. So a new common protocol has been created: messages.

Messages can be reported as ndjson, and that protocol is shared across all implementations. Some tooling exists to convert ndjson messages into a json that looks pretty close to the legacy json formatters.

At first we wanted to totally deprecate the json formatters. But as so many users are relying on it, we will keep it, but letting it in maintenance mode.

Also, messages do have all the timing data you need. Please give it a try. To get messages, use `--format message`

json formatter can be nice to share with humans.
But the message formatter will be better to work with when interacting with other programming tools. Here's the documentation for messages: https://github.com/cucumber/common/blob/main/messages/messages.md

**Comment by aurelien-reeves** [comment]
@vctqs1 did you had the opportunity to take a look on the "message" formatter for your project?

I think the "message" formatter may better fit your needs.

**Comment by vctqs1** [comment]
> @vctqs1 did you had the opportunity to take a look on the "message" formatter for your project?
> 
> I think the "message" formatter may better fit your needs.

My team's trying to convert to message formatter. THANKS for your support. Hope I can contribute next time .

I'll close this PR. Many thanks again

**Comment by aurelien-reeves** [comment]
Thanks @vctqs1 for your contribution, that was helpful in any case!

If you encounter any issue with the messages, please feel free to ask! Are you already on the cucumber community slack? If not, you can register for an account here: https://cucumberbdd-slack-invite.herokuapp.com/. You'll find plenty of help there :)

**Pull request closed without merging**
