### PR TITLE
Scenario outline with examples in title

### PR DESCRIPTION
**Pull request by chrismilleruk**
Fix for issue #267 to bring behaviour inline with Cucumber-JVM

### CODE REVIEW

**Comment by riaan53** [comment]
Hi @jbpros  - do you still plan to merge this? I do lots of metrics testing and this will help a lot :)

Great job on cucumber.js to the team btw!

Regards,
Riaan

**Comment by jbpros** [comment]
@riaan53 yes, it's going to be merged.

@chrismilleruk I see no changes to the ScenarioOutline specs in this PR (I'm surprised it's all passing). Can you update them? I can help if you want.

**Comment by unwitting** [comment]
Can this be pulled please? I'm really jonesing for examples in multiline strings :\

**Comment by jbpros** [comment]
Merged in as 4673a59.

**Pull request closed without merging**
