### PR TITLE
Add generator support 

### PR DESCRIPTION
**Pull request by golya**
It solve the #438.

### CODE REVIEW

**Comment by golya** [comment]
@charlierudolph Can you help me about how I should solve this build error? What is the guideline for ES6 features?

**Comment by charlierudolph** [comment]
Hmm, so we need to find a way to ignore this feature when running on node 0.10 and 0.12. Thats most easily accomplished with tags but I don't think we can do anything programmatic here. We may need to just use a different test command for running those versions, so we can pass the CLI a flag to ignore the feature. Looks like we need the more explicit way of including jobs to the build matrix.

https://docs.travis-ci.com/user/customizing-the-build/#Explicity-Including-Jobs

**Comment by golya** [comment]
@charlierudolph what about process.version? Or do you want to avoid that put version handling to the source?

**Comment by charlierudolph** [comment]
How exactly would you use process.version?

**Comment by charlierudolph** [comment]
Got the build passing on a branch I created off your work
https://github.com/cucumber/cucumber-js/compare/cr-golya?expand=1
This was what I envisioned for how to deal with the feature tests.
If you have another idea for how to deal with them via process.version, please let me know.


Once you merge with master you should see some unit tests for the runner (which I extracted today). 
Hopefully we can add some unit tests for generators and use process.version to ignore them on 0.12 and 0.10.

**Comment by golya** [comment]
@charlierudolph I merged with the latest master and I used your suggestions. But the unit test is not really cool. I had to use eval to avoid the Unexpected token error in case of the old versions of the node. Can you check it? I think we should remove the last patch which contains this unit test and let the feature tests to force that it be able to use generators.

**Comment by charlierudolph** [comment]
Okay I'm fine removing the unit test. Could you please also move the test to a new feature file? Maybe `es6.feature`

**Comment by golya** [comment]
The unit test is removed, and the feature test is moved to es6.feature.

**Pull request closed without merging**
