### PR TITLE
Regexp to cucumberexp

### PR DESCRIPTION
**Pull request by shvmsnju**
### 🤔 What's changed?

Changed 3 instances of regular expressions in the step definitions with cucumber expressions

### ⚡️ What's your motivation? 

The change is a small step in fixing issue #1871 

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt (improvement to code design or tooling without changing behaviour)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by shvmsnju** [comment]
Hi @mattwynne, in the cli.steps.ts file in step-definitions, 
when i try to change  When(  /^I run cucumber-js \(installed (locally|globally)\)$/ ........
to When('I run cucumber-js \(installed (locally|globally))' it is showing linting problem (no-useless-escapes) 
How do we change this kind of regexp to cucumber expressions

**Comment by davidjgoss** [comment]
> If you look at [the step definition](https://github.com/cucumber/cucumber-js/blob/main/features/step_definitions/cli_steps.ts#L83) it just has a big if statement around it anyway, so I'd just split this into two step definitions each with a hard-coded locally or globally.

+1 I think this is the cleanest way.

**Comment by mattwynne** [comment]
@shvmsnju since this stands as a good change on its own, I'll merge it in and you can deal with [this issue](https://github.com/cucumber/cucumber-js/pull/1926#issuecomment-1045963883) in a separate PR, OK?

**Review by mattwynne — APPROVED** [review]

**Comment by shvmsnju** [comment]
> @shvmsnju since this stands as a good change on its own, I'll merge it in and you can deal with [this issue](https://github.com/cucumber/cucumber-js/pull/1926#issuecomment-1045963883) in a separate PR, OK?

@mattwynne yes of course! I was just a busy with work so i was not able to do that untill now. Will try to do that during this weekend!

**Comment by shvmsnju** [comment]
Hi @mattwynne,

Even if we break the step definition into two parts, When we implement the step definition like: 

When('I run cucumber-js \(installed locally\)',{ 

Eslint will not allow escaping the bracket using \ as we don't need it in regular string and eslint considers this as a useless escape character and removes it when we save the file. To escape the bracket so that it is considered as a literal bracket and not optional text in cucumber expression we need to escape the \ character before the bracket using another \. I guess the whole thing sounds pretty confusing but you will understand when u see the code. I ran the tests and they are passing.

**Pull request merged**
